### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by alixeb** [luggit/react-native-config#100]
Hello,

Has anyone tried to use this on Windows OS?
Any plan to support Windows?
Any plan to update README with Windows steps?

Much appreciated

**Comment by atlanteh** [comment]
I'm creating an android app on windows and it works great for me. Can you describe what ur problem is?

**Comment by alixeb** [comment]
I am talking about support for Windows App, i.e react-native-windows.

Does this repo allow you to have config on windows app, the same way it does for Android app or iOS app?

**Comment by atlanteh** [comment]
ah, then I don't think it currently supports it. If you understand windows programing, you can probably create a PR, otherwise, you need to wait for someone else to implement this.

**Comment by vvkaghera** [comment]
Does it supports on Windows Mobile App?
