### ISSUE TITLE
[RFC] Better support for Info.plist and Xcode

### ISSUE THREAD

**Issue by migueloller** [luggit/react-native-config#101]
### Background
After doing a lot of research into [Xcode's project file format](https://github.com/alunny/node-xcode), [Xcode configurations](https://medium.com/@danielgalasko/run-multiple-versions-of-your-app-on-the-same-device-using-xcode-configurations-1fd3a220c608) and  [`rnpm`](https://github.com/rnpm/rnpm), I've come up with a way to support Xcode configurations that might be worth considering.

The latest release ([v0.2.0](https://github.com/luggit/react-native-config/releases/tag/v0.2.0)) added experimental support for `Info.plist` files but still requires a [manual step](https://github.com/luggit/react-native-config#extra-step-for-ios-to-support-infoplist) during configuration. This proposal removes the need for that extra step and mirrors the use of the battle-tested [`dotenv`](https://github.com/motdotla/dotenv) that inspired this library.

This change should also fix the following issues: https://github.com/luggit/react-native-config/issues/6 and https://github.com/luggit/react-native-config/issues/60.

### Proposal
The proposed way to use the API would be to run `rnconfig` (we can bikeshed on the appropriate name) right before running or building the React Native project.

It would be used like this:
```bash
react-native start
rnconfig && react-native run-ios ; rnconfig --clear
```

This workflow is not unsimilar to `dotenv`'s `node -r dotenv/config .`. It could also potentially unify the way to define different `.env` files (passed as a parameter to `rnconfig`) if a similar workflow is used for Android.

### Workflow
- `react-native link` sets up the native dependency so that you can `import Config from 'react-native-config'`.
- `rnconfig` copies the contents of `.env` (or any file that could be specified as an arg) into the Xcode project using [`xcode`](https://github.com/alunny/node-xcode). If the `clear` flag is set then the variables are removed (this is also up for discussion). The purpose of `clear` is to keep the variables out of version control.

I'll send a PR soon that shows this in practice. For now, I'd love to hear of what people think about this idea.

cc: @pedro

**Comment by pedro** [comment]
Hi @migueloller! Sorry for the delay chiming in here.

I like this direction, it's clearly miles away from what we have today! Posting in #104 some thoughts on this as well as the other approach discussed there.

**Comment by pedro** [comment]
Hi @migueloller! Sorry for the delay chiming in here. I like this direction, it's clearly miles away from what we have today!

Do you think we can still make this work for people developing from Xcode though? Like, if I just run a scheme can I make it do the `rnconfig` call/pick the right env? Or any other thoughts on how to make this work both from Xcode and `react-native run-ios`?

The use for `--clear` is interesting, could we just ask people to put that file in `.gitignore` instead? Or maybe have that file live in a folder that is already ignored by react-native's default `.gitignore`? For instance somewhere in build.

Sorry for the pretty generic/aspirational questions 😬 I'm not very familiar with Xcode. But good stuff in #104 too, going to check it out as well.

**Comment by migueloller** [comment]
@pedro,

With regards with `--clear` it's because Xcode user-defined build configuration values are stored inside the project and you can't ignore the entire project.

As for people running from Xcode I think that what I mentioned in https://github.com/luggit/react-native-config/issues/104#issuecomment-297516348 might be the best direction. I didn't think of that before.

Basically the process would be to simply run `react-native link react-native-config` and that will do 2 things, link the native dependency as usual and add a build script that will generate the environment variables. My only worry is cleaning up the project afterwards.

Perhaps it's worth looking into how Xcode manages secrets. I think it's possible to store them in `xcuserdata` which is a folder React Native already ignores. If that's the case then instead of storing the values in the project, they would be stored there, which would solve the issue of publishing secrets to version control.

**Comment by pedro** [comment]
Amazing, it seems like this could work quite well! Let me know if you find the time to give it a try. Like I said in #104 I'm happy to make you an owner of this package if this interests you and you want to own this front!

Thanks,

**Comment by pedro** [comment]
Closing for now, open to any further thoughts/experiments here! :+1:
