### ISSUE TITLE
Xcode project file: The file couldn't be opened

### ISSUE THREAD

**Issue by scandinaro** [luggit/react-native-config#105]
After running `react-native link react-native-config` my xcode project is corrupted and and only seems to be able to be fixed by reverting changes to `ios/LGSAppRedux.xcodeproj/project.pbxproj` which undoes the linking.

**Comment by eugenehp** [comment]
@scandinaro I found similar issue to it later, and found that fixes like https://github.com/eugenehp/react-native-config/commit/9792326107a3204110c723dfee244f8d067bb786 helped to get over it.

**Comment by scandinaro** [comment]
Yes, thank you...I just starting debugging lines change in .pbxproj until I figured out which lines were causing the issue.
