### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by bernatfortet** [luggit/react-native-config#107]
I've followed the config steps.
When I run the build I get this error:
`Syntax Error ... Unexpected token (23:0)`

The line #23 it's refers to the `ENVIRONMENT == 'DEVELOPEMENT'` below

```js
import Config from 'react-native-config'
const ENVIRONMENT = Config.ENVIRONMENT
```
...
```js
const fbMikey = null
else if( ENVIRONMENT == 'DEVELOPEMENT')
  fbMikey = firebase.initializeApp(firebaseMikeyDevelopmentConfig, 'mikey_dev' )
```

Any idea?
Thanks

**Comment by pedro** [comment]
hmm, it seems like you have an `else` without a preceding `if` there!
