### ISSUE TITLE
Is it possible to use it in project.pbxproj file?

### ISSUE THREAD

**Issue by junedomingo** [luggit/react-native-config#109]
I want to dynamically change the Bundle Identifier. Is this possible? if so, how?

**Comment by eugenehp** [comment]
@junedomingo I think it's outside of the scope of `react-native-config` but if you'd want to achieve that functionality, you'd probably end up with scripting it using something like fastlane or bash.

**Comment by junedomingo** [comment]
I see. I think i will end up using `bash`.

**Comment by grifotv** [comment]
@junedomingo would you mind sharing your solution to change the Bundle Identifier using `bash`? thanks
