### ISSUE TITLE
React Packager stops working after linking library

### ISSUE THREAD

**Issue by dpikt** [luggit/react-native-config#114]
After linking the library, React Packager freezes on subsequent launches.

Commands I ran:
1. `yarn add react-native-config`
2. `react-native link react-native-config`
3. `react-native run-ios`

React packager hangs on the line `Loading dependency graph, done.` and the app fails to launch in the simulator. However, it will still successfully launch from XCode, as well as if I unlink the library.

For reference, I'm using react native v0.43.4 and react-native-config v0.4.2.

**Comment by pedro** [comment]
Hi there! Can you give it a try against the latest version, 0.11?

Let me know if the problem persists!

Thanks,
