### ISSUE TITLE
BUG ANDROID

### ISSUE THREAD

**Issue by 2ducanhpham** [luggit/react-native-config#118]
IOS it ok, but android not ok.
my file .env 
URL=localhost:3000

I used to "import Config from  "react-native-config" in js code
-> IOS then Config = {URL="localhost:3000" }
-> Android then Config = {}

**Comment by aindeev** [comment]
Is there any news or workarounds on this?

**Comment by abrantes01** [comment]
I had the same issue too, fixed following some instructions provided here : https://github.com/luggit/react-native-config/issues/32

Don't forget this part https://github.com/luggit/react-native-config#extra-step-for-android on Android setup, looks like `react-native link` command was not adding the line automatically.

**Comment by 2ducanhpham** [comment]
Not working, I'm waiting for the new version

**Comment by ozsirma** [comment]
You can check these codes in MainApplication.java. If it is not exist, you can add them

import com.lugg.ReactNativeConfig.ReactNativeConfigPackage; // add
...
return Arrays.<ReactPackage>asList(
   ...
   new ReactNativeConfigPackage(); // add
);

**Comment by hdchan** [comment]
@ozsirma where are you calling new ReactNativeConfigPackage();

**Comment by chrusart** [comment]
@hdchan, as @ozsirma wrote in MainApplication.java:
```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.asList(
        ...
        new ReactNativeConfigPackage(),
        ...
      );
    }
``

**Comment by jariwalabhavesh** [comment]
@ozsirma @chrusart 
I am also facing same issue
It is there in MainApplication.java still it is not working in android it is giving  config={}

**Comment by Sundin** [comment]
Allright, following the above suggestions + adding this line to `android/app/proguard-rules.pro` solved it for me:

`-keep class com.mypackage.BuildConfig { *; }`

Basically following the readme in other words 😄

**Comment by elyobo** [comment]
@ozsirma Thanks, that was my problem :+1:

**Comment by pedro** [comment]
Thank you folks! Closing then, let me know if the problem persists.

**Comment by conor909** [comment]
@Sundin I still get `error: package com.lugg.ReactNativeConfig does not exist`

**Comment by leoderigo** [comment]
> @Sundin I still get error: package com.lugg.ReactNativeConfig does not exist
> Is this package being maintained? Anyone know of an alternative?

@conor909  Did you fix this error? How did you do?

**Comment by ditorahard** [comment]
In case anyone needed it here : 

I solved it by changing MainApplication.java code imports : 
 
`import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;`

to :

`import com.lugg.RNCConfig.RNCConfigPackage;`

**Comment by ArayomiWork** [comment]
> 

I LOVE YOU MAN THANK YOU SO MUCH

**Comment by ArayomiWork** [comment]
> In case anyone needed it here :
> 
> I solved it by changing MainApplication.java code imports :
> 
> `import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;`
> 
> to :
> 
> `import com.lugg.RNCConfig.RNCConfigPackage;`

I LOVE YOU MAN THANK YOU SO MUCH

**Comment by 29er** [comment]
> In case anyone needed it here :
> 
> I solved it by changing MainApplication.java code imports :
> 
> `import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;`
> 
> to :
> 
> `import com.lugg.RNCConfig.RNCConfigPackage;`

yes many thanks. the RNC documentation is out of date!

**Comment by AhteshamKhanCoder** [comment]
I solved it by changing MainApplication.java 
import this import com.lugg.RNCConfig.RNCConfigPackage;
instead of  import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;

and use package 
 new RNCConfigPackage(); 

instead of
new ReactNativeConfigPackage()
