### ISSUE TITLE
BuildDotenvConfig.ruby:21:in `split': invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by denghejun** [luggit/react-native-config#119]
I build in XCode after install and linked the react-native-config, and I got a build error below:

```
ReactNativeConfig/BuildDotenvConfig.ruby:21:in `split': invalid byte sequence in US-ASCII (ArgumentError)
	from ./ReactNativeConfig/BuildDotenvConfig.ruby:21:in `<main>'
```
could you guys help me to fix this?

**Comment by denghejun** [comment]
<img width="786" alt="screen shot 2017-05-24 at 5 46 31 pm" src="https://cloud.githubusercontent.com/assets/8454695/26404728/8511fe3a-40c5-11e7-8755-338032a83b00.png">

**Comment by denghejun** [comment]
sorry, this is not a bug, I have some special symbol. It works normal after I remove the special symbol.

**Comment by askiiRobotics** [comment]
Actually it IS a bug when you need to add some UTF-8 simbols to your config.
