### ISSUE TITLE
[iOS] Follow all the steps but still getting empty Config object

### ISSUE THREAD

**Issue by zoranmarjanovic** [luggit/react-native-config#127]
So base on instructions I have setup my build settings in xcode like this http://prntscr.com/fmv0c5
Created schema with pre actions http://prntscr.com/fmv11f
added config file in root folder : http://prntscr.com/fmv3rr

Also before that I have run react-native link
And after all these steps when I run from xcode with selected dev schema, Config object is empty in js code.

Any clue?

**Comment by zoranmarjanovic** [comment]
Found kind a solutions, I have downgrade react-native-config to 0.3.0 from 0.5.0, but not sure what is wrong with 0.5.0 :/

**Comment by pedro** [comment]
Odd, wonder if we had a regression in 0.5 but glad you figured it out a workaround!
Things should be working again in 0.11 but let me know if not!
