### ISSUE TITLE
Can't we have an node js file to BuildDotenvConfig to iOS?

### ISSUE THREAD

**Issue by sibelius** [luggit/react-native-config#13]
https://github.com/luggg/react-native-config/blob/master/ios/ReactNativeConfig/BuildDotenvConfig.ruby

It makes much more sense to use a js file so we don't have to install ruby in our system

**Comment by erickreutz** [comment]
Would love a pull request!

**Comment by greg5green** [comment]
So I started spent a little of my spare time doing this, first starting with NodeJS and moving to Bash after figuring out it wasn't super easy to have Xcode do a build script with NodeJS (or at least I had trouble figuring it out), but recently had the thought -- what does this gain? Don't all OS X installs include Ruby?

**Comment by rturk** [comment]
@sibelius this is a great idea, I wouldn't like to see a normalized code that somewhat could be reused/shared between Androd and IOS.

**Comment by pedro** [comment]
+1, would be awesome to extract the code to parse env (prob just using the `dotenv` package) and later reuse it for both Android and iOS.

Closing for now but def welcome for patches on this front!

**Comment by sibelius** [comment]
try this one https://github.com/zetachang/react-native-dotenv
