### ISSUE TITLE
Running on CMD Windows 

### ISSUE THREAD

**Issue by mohamed-habib** [luggit/react-native-config#132]
On CMD, when i run the command `SET ENVFILE = '.env.staging' && react-native run-android`  it works well and builds the staging version, but when i run the command `react-native run-android` on the same CMD window, it doesn't use the default as it's supposed to, it uses the staging again,
the same problem happen when i close the current CMD window and the the command, it still uses the staging version.

However, the problem doesn't happen on PowerShell when i close the window and open another one to run the different command.

**Comment by Assem-Hafez** [comment]
This is because the command have spaces arround the `=`. removing the spaces should make the command execute correctly `SET ENVFILE='.env.staging' && react-native run-android`. The readme is now updated and spaces was removed #147.

**Comment by pedro** [comment]
:+1:! Thank you @Assem-Hafez
