### ISSUE TITLE
RN 0.47 android build error

### ISSUE THREAD

**Issue by kidnapkin** [luggit/react-native-config#139]
The build is failing after updating project to RN 0.47.1
Same is for the brand new project:

```
/home/user/Desktop/project/node_modules/react-native-config/android/src/main/java/com/lugg/ReactNativeConfig/ReactNativeConfigPackage.java:21: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-config:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-config:compileReleaseJavaWithJavac'.

```

**Comment by theohdv** [comment]
It has been fixed in this [commit](https://github.com/luggit/react-native-config/commit/4d8ffdb995e93e3516c9909680d49d508c4c6f64) I assume but it has not been released yet. So if you need it now you can import master repo directly.

**Comment by GantMan** [comment]
I just released `0.6.0` and tested it.  Should be good now @kidnapkin

**Comment by pedro** [comment]
:+1:! Thank you folks!

**Comment by philjoseph** [comment]
Is that fixed not yet released?
