### ISSUE TITLE
react-native-config:compileReleaseJavaWithJavac Failed

### ISSUE THREAD

**Issue by arvenjadeaguilar** [luggit/react-native-config#141]
I have followed everything on the instruction but when I tried to run it. It gives me this error 

:react-native-config:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

android/src/main/java/com/lugg/ReactNativeConfig/ReactNativeConfigPackage.java:13: error: ReactNativeConfigPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class ReactNativeConfigPackage implements ReactPackage {
       ^

Can anyone please help me how to resolve this? thanks

**Comment by gijoehosaphat** [comment]
Guessing this is related to react-native 0.47.0 and their breaking chance w/ createJSModules?

**Comment by Natalishka** [comment]
I have the same problem:
here is my package.json fragment:
"dependencies": {
    "react-native": "0.44.2",
    ......
    "react-native-config": "^0.6.0"
  }

**Comment by jayarprado** [comment]
Same problem here.
```
"react-native": "^0.46.4"
"react-native-config": "^0.6.0"
```

**Comment by mamdouh-mowesolutions** [comment]
it's now working for me with:
react-native: 0.45.1,
and "react-native-config": "^0.5.0"

I checkout old version of because 0.6.0 cause problem with react-native: 0.45.1.

**Comment by arvenjadeaguilar** [comment]
I checkout the older version and its working fine. I use the 0.5.0 as what @mamdouh-mowesolutions  stated

**Comment by IanEdington** [comment]
This seems to be due to an breaking change in react-native 0.47. This was fixed in #137 for version 0.6.0 of react-native-config. 

My understanding is you need to update in lock set react-native 0.47 with 0.6 of this package. This is true for a lot of packages with 0.47 of react.

Basically use:

	react-native: "<0.47",
	react-native-config: "<0.6.0"

or

	react-native: ">=0.47",
	react-native-config: ">=0.6.0"
