### ISSUE TITLE
ReactNativeConfigPackage is not abstract and does not override abstract method createJSModules() in ReactPackage

### ISSUE THREAD

**Issue by Neglexis** [luggit/react-native-config#154]
```
/.../node_modules/react-native-config/android/src/main/java/com/lugg/ReactNativeConfig/ReactNativeConfigPackage.java:13: error: ReactNativeConfigPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class ReactNativeConfigPackage implements ReactPackage {
       ^
1 error
:react-native-config:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-config:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by mike623** [comment]
This PR #144 fix problem but need to merge ASAP

**Comment by amikofalvy** [comment]
Agreed. I am also waiting on this PR to be merged.

**Comment by amikofalvy** [comment]
This issue was resolved when #144 was merged.

**Comment by pedro** [comment]
:+1:!

**Comment by saurabhspatil** [comment]
error: ReactNativeContacts is not abstract and does not override abstract method createJSModules() in ReactPackage
public class ReactNativeContacts implements ReactPackage {
       ^
1 error
:react-native-contacts:compileReleaseJavaWithJavac FAILED
 
On
react-native-cli: 2.0.1
react-native: 0.46.0

**Comment by abdalafer** [comment]
@saurabhspatil did you find a solution?

**Comment by saio3139** [comment]
error: ReactNativeContacts is not abstract and does not override abstract method createJSModules() in ReactPackagepublic class ReactNativeContacts implements ReactPackage {^1 error:react-native-contacts:compileReleaseJavaWithJavac FAILED
--

Got this module working by adding the following to ReactNativeContacts.java.

import com.facebook.react.bridge.JavaScriptModule;

@Override public List<Class<? extends JavaScriptModule>> createJSModules() { return Collections.emptyList(); }

**Comment by BhatMonu** [comment]
I am still getting this error

:react-native-contacts:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
C:\Users\Oserlab\Desktop\YC_ReactNative\youngclay\node_modules\react-native-contacts\android\src\main\java\com\rt2zz\reactnativecontacts\ReactNativeContacts.java:13: error: ReactNativeContacts is not abstract and does not override abstract method createJSModules() in ReactPackage
public class ReactNativeContacts implements ReactPackage {
       ^
1 error
:react-native-contacts:compileReleaseJavaWithJavac FAILED

I am using:-
 "react-native-contacts": "1.0.4",
 "react-native": "0.46.0",
 "react-native-cli": 2.0.1
