### ISSUE TITLE
[Gradle] Do not force use of ENVFILE for basic commands

### ISSUE THREAD

**Issue by Andreyco** [luggit/react-native-config#158]
When running very basic commands such as `gradlew tasks` command fails since no ENVFILE is specified.

Not sure about proper solution. Maybe fallback to "debug" configuration (if found) and inform user about this fallback.

**Comment by pedro** [comment]
This should be working as expected now – running without ENVFILE will just make it read from `.env` (as much as it doesn't matter if you're just running `gradlew tasks`).

Let me know if you can think of a way to not load our dotenv unless building the actual app!

**Comment by zaguini** [comment]
+1
