### ISSUE TITLE
Can't upload iOS app

### ISSUE THREAD

**Issue by alonsotagle** [luggit/react-native-config#161]
Everything works fine even install the app in a device, but when I tried to upload my app to App Store I got the next error.
It worked before add this module.

![image](https://user-images.githubusercontent.com/2649151/30712677-73802a32-9ed2-11e7-9e3d-c6c4d0cab1d7.png)

Xcode 8.3 (8E162)
React 16.0.0-alpha.12
React Native 0.47.1
React Native Config 0.6.1

Do you have any idea why is this happening?

P.D. I've already follow all the setup instructions

Thanks

**Comment by pedro** [comment]
This is just xcode being xcode, not related to this package (:

I take you tried restarting it? Does it work if you export the app and use the application loader to upload it instead of xcode?

**Comment by alonsotagle** [comment]
Restart and check again the App Store and found a Xcode update, sorry 😅

**Comment by pedro** [comment]
No worries! Glad it's sorted out
