### ISSUE TITLE
Android: Staging env file under releaseStaging with Code Push

### ISSUE THREAD

**Issue by aminy** [luggit/react-native-config#175]
On android, I have a two 3 env files:
.env -> for debug/local
.env.staging -> for staging environment
.env.production -> for production environment

The difference between the staging and production as basically the end points they use, but I can't get the react-native-config to read the staging file.

I also have 3 build type:
- debug
- release
- releaseStaging

I'm using code push with different keys for release and releaseStaging variants.

Here is what I have in my build.gradle file for envConfigFiles:
```
project.ext.envConfigFiles = [
    releaseStaging : ".env.staging",
    release: ".env.production",
    anycustombuildlowercase: ".env",
]
```

When I build/run the app using variant releaseStaging
```
react-native run-android --variant=releaseStaging
```
I expect to use `.env.staging` file but it's using `.env.production`.

I think the issue is in `dotenv.gradle` file were we are looking at the flavour of the build and matching `releaseStaging` with `release`

**Comment by mauron85** [comment]
I guess you're missing releaseStaging section in `android/app/build.gradle`

```
    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            // Note: CodePush updates should not be tested in Debug mode as they are overriden by the RN packager. However, because CodePush checks for updates in all modes, we must supply a key.
            buildConfigField "String", "CODEPUSH_KEY", '""'
        }
        releaseStaging {
            minifyEnabled enableProguardInReleaseBuilds
            signingConfig signingConfigs.releaseStaging
            buildConfigField "String", "CODEPUSH_KEY", '"staging_key_here"'
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            buildConfigField "String", "CODEPUSH_KEY", '"production_key_here"'
        }
..
```

**Comment by connercms** [comment]
I was running in to the same issue. I tried the above and it didn't work. What eventually worked for me was changing 

```
project.ext.envConfigFiles = [
    ...
    releaseStaging : ".env.staging",
    ...
]
```
To 
```
project.ext.envConfigFiles = [
    ...
    stagingrelease : ".env.staging",
    ...
]
```

Then adding stagingrelease under buildtypes and running react-native run-android --variant=stagingrelease. They put emphasis on making all custom builds all lowercase. Not sure why it matters but using stagingrelease vs releaseStaging fixed it for me.

**Comment by pedro** [comment]
:+1:! @connercms solution above should work.

I think we compare variants in lowercase because depending on how you invoke Gradle the  names could be mixed up. We can probably enhance how we extract the variant to avoid this issue in 1st place, but not too familiar with Gradle to know 😬

**Comment by youngjuning** [comment]
@pedro any best practice?

**Comment by kodayashi** [comment]
Yeah react source expects the release token in the built variant or hilarity ensues:

```javascript
def devEnabled = !targetName.toLowerCase().contains("release")
if (Os.isFamily(Os.FAMILY_WINDOWS)) {
    commandLine("cmd", "/c", *nodeExecutableAndArgs, "node_modules/react-native/local-cli/cli.js", "bundle", "--platform", "android", "--dev", "${devEnabled}",
            "--reset-cache", "--entry-file", entryFile, "--bundle-output", jsBundleFile, "--assets-dest", resourcesDir, *extraPackagerArgs)
} else {
    commandLine(*nodeExecutableAndArgs, "node_modules/react-native/local-cli/cli.js", "bundle", "--platform", "android", "--dev", "${devEnabled}",
            "--reset-cache", "--entry-file", entryFile, "--bundle-output", jsBundleFile, "--assets-dest", resourcesDir, *extraPackagerArgs)
}
```

So make sure you have the "release" token at the end of each custom variant.

**Comment by MarceloPrado** [comment]
Regarding @kodayashi comment, this is not entirely true anymore. React Native now has [another](https://github.com/facebook/react-native/blob/1a67dda668c71d961a4bb3b0cdf6aa22c0e5c138/react.gradle#L159-L160) option to toggle the release variant.

To use it, you must declare a `project.ext.react` at the top of your `android/app/build.gradle` file. An example usage looks like this:

```gradle
project.ext.react = [
    ...
  
    // Staging build example
    devDisabledInStaging: true,
]
```

Notice the "Staging" suffix. It needs to match you build type.

**Comment by hoyoungmoon** [comment]
```
project.ext.envConfigFiles = [
    debug : ".env.debug",
    release : ".env.release",
    releasestaging : ".env.staging"
]
```
To
```
project.ext.envConfigFiles = [
    debug : ".env.debug",
    releasestaging : ".env.staging",
    release : ".env.release"
]
```
just switch order of `release` and `releasestaging`
(`releasestaging` must be lowercase)
