### ISSUE TITLE
[Android] Build with fast lane, always take .env

### ISSUE THREAD

**Issue by batical** [luggit/react-native-config#178]
Hello,

I managed to make it work on IOS(I have 2 targets which 2 schemes so I could not use a pre compilation step). Instead I made the same script into an sh() at the beginning in fast lane

For android, I was not able to make it working with flavors. I want back having 3 buildTypes.
After looking all the tricks here, (renaming build types, removing caps etc etc) I made it work  if I am building from Android studio(not always working)

`project.ext.envConfigFiles = [
        debug: ".env.dev.debug",
        staging: ".env.staging",
        release: ".env"
]`

Using fast lane, I ALWAYS use .env ([12:33:32]: ▸ Reading env from: .env)
I tried the same trick doing sh(ENVFILE=.env.staging) but not working, 

The only trick I found for now, i removing the envConfigFile from the gradle file and calling fastlane 
ENVFILE=.env.staging fastlane lanetobuild

Any idea on what I missed ? Because if I want to build with android studio, I have to uncomment the nvConfigFile, to build with fast lane, I have to comment it and une ENFILE=.env.staging at the beginning of the command

**Comment by hdchan** [comment]
I created a pull request to address this: https://github.com/luggit/react-native-config/pull/180

**Comment by batical** [comment]
I don't use buddyBuild :) I will have a look at you PR, but I have too many issue that I am considering doing something myself (little ugly I am sure) but....
between  adding 
- sh(echo .env.staging > /tmp/envfile) in fastlane ios
- sh(ENVFILE=.env.staging) in fasrtlane android and not working,  that's finally I am doing ENVFILE=.env.staging fastlane lane
- Having the comment/uncomment in my graddle file
- adding ENVFILE=.env.staging front of my react-native command


There is too many tricks that I don't feel confident using.  I have a simplier project coming in, maybe I will give a try

Nevermind, thanks for all your work

**Comment by alizahid** [comment]
@hdchan I think #180 broke something.

`./gradlew assembleStaging` just reads from `.env` now.

**Comment by seunlanlege** [comment]
just ran assemblestaging, and it's is reading from `.env`
