### ISSUE TITLE
regression- can't set files for different enviornments with project.envConfigFiles in android 

### ISSUE THREAD

**Issue by alonbardavid** [luggit/react-native-config#183]
the commit : https://github.com/luggit/react-native-config/commit/be8d77e501733430fddb351bdebddc9d3a736700#diff-8d06eb7310a0fb4c699d3b2bc827e06a broke the project.ext.envConfigFiles option to define different config files for android.

`currentFlavor` is always `.env` since that is what is passed to `loadDotEnv` now

**Comment by pedro** [comment]
hmm /cc @hdchan if you have any thoughts/ideas

**Comment by hdchan** [comment]
Hm not quite sure what is happening, I mean you can roll it back if it's breaking for a number of people. Sorry about that.

**Comment by pedro** [comment]
Should be fixed in 0.11.1!

Thanks folks
