### ISSUE TITLE
v0.10.0 does not work anymore 

### ISSUE THREAD

**Issue by AlmogRnD** [luggit/react-native-config#189]
Just tried upgrading to v10.0.0 the upgrade was fine but when I tried to console.log the config var I got empty values had to downgrade back to v0.9.1 which worked fine

**Comment by FredericRuaudel** [comment]
Same here !

**Comment by phuochau** [comment]
same problem too +1

**Comment by SrdjanCosicPrica** [comment]
I haven't tried earlier versions than 0.10.0 but I feel like this might related to this issue.

I have two different environment filer. **.env.development** and **.env.production**.
My android **build.gradle**
```
project.ext.envConfigFiles = [
        debug: ".env.development",
        release: ".env.production"
]
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
```
Running the command
```
react-native run-android
```
I get the following output.
```
> Configure project :app
Reading env from: .env
**************************
*** Missing .env file ****
**************************

> Task :app:generateDebugBuildConfig
Reading env from: config/.env.development

```

My **.env.development** has a simple variable
```
API_URL='localhost'
```
and I am trying to log it with `console.log()` but it is declared undefined.

The interesting thing is that if I run this command however
```
ENVFILE=.env.development react-native run-android
```
It logs the variable correctly.
This is only tested with android as I can't test for IOS at this moment. But like I said, have not tested with earlier versions. I will go back to 0.9.1 like @AlmogRnD mentioned and leave this information here in case it is related to a v.0.10.0 bug.

**Comment by samermurad** [comment]
It's broken because of this commit, I removed the following described line in the ruby script and it fixed it
https://github.com/luggit/react-native-config/commit/be8d77e501733430fddb351bdebddc9d3a736700

**Comment by AlmogRnD** [comment]
Has this been merged into the release

**Comment by pedro** [comment]
Hey folks! Sorry for the trouble, can you try updating to 0.11.1?

Let me know if any issues persists. I updated the example apps to the latest RN so should be easier to detect issues like this going forward.

Thanks,

**Comment by samermurad** [comment]
Working! Thanks for the effort!

**Comment by Ayyagaries** [comment]
still not working I am using 0.11.5 

> Configure project :app
Reading env from: .env
**************************
*** Missing .env file ****
**************************
