### ISSUE TITLE
[iOS] Setting AppIcon with RN Config

### ISSUE THREAD

**Issue by Aidurber** [luggit/react-native-config#197]
Hi, 

I've been fighting with this all morning, is it possible to set the AppIcon (ASSETCATALOG_COMPILER_APPICON_NAME) with my env file?

I have 3 sets of App Icons: 
 - AppIcon.trs
 - AppIcon.tfs
 - AppIcon.pma

I've tried: 
`__RN_CONFIG_APP_ICON` directly in the asset catalog app icon name. 
I've tried defining a IOS_APP_ICON variable in the Info.plist and using it like: 
`$(IOS_APP_ICON)` and `${IOS_APP_ICON}`

The guides I've seen around ([Different App Icons for your iOS Beta, Dev, and Release builds | Circle Engineering](https://engineering.circle.com/different-app-icons-for-your-ios-beta-dev-and-release-builds-af4d209cdbfd)) all use Build Targets to define, which would work. But I need to use Schemes or the Env file. 

Any guidance would be awesome. :heart:

**Comment by Ashwin-Mothilal** [comment]
Have you done this?

**Comment by Aidurber** [comment]
Hi @Ashwin-Mothilal 
I did but not using RN Config. 
I created multiple build configurations i.e.

Paid.debug
Paid.release
Free.debug
Free.release

I created a user defined variable in my targets' build setting called APP_NAME_SUFFIX

| Build Config  | APP_NAME_SUFFIX |
| ------------- | ------------- |
| Debug  |  |
| Release  |  |
| Free.Debug | .free |
| Free.Release | .free |
| Paid.Debug | .paid |
| Paid.Release | .paid |


Then in **Asset Catalog App Icon Set Name** double click where it says `<Multiple values>`
and enter: `AppIcon${APP_NAME_SUFFIX}`. 

Create multiple app icons with the target suffixes like: AppIcon.free

You could go even further with your APP_NAME_SUFFIX such as: 
`.free.debug`
To have more variations in your icons. 

I hope this helps.

**Comment by shwanton** [comment]
👍 Thanks for this follow-up... I tried every permutation of RN config var with no luck. Once I followed these instructions, everything worked!
