### ISSUE TITLE
Android release app not process environments as production

### ISSUE THREAD

**Issue by francisrod01** [luggit/react-native-config#202]
I just discover this running `react-native log-android` while the emulator are running.

```
12-22 20:31:35.407  2102  2122 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
12-22 20:31:35.638  2102  2121 I ReactNativeJS: '==== API_URL: ', undefined
12-22 20:31:35.818  2102  2121 I ReactNativeJS: Running application "BDReactNativeApp" with appParams: {"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON

```

My `api.js` file is below:

```js
import axios from 'axios'
import Config from 'react-native-config'


const api = axios.create({
    baseURL: Config.API_URL
})


console.log('==== API_URL: ', Config.API_URL)
...
```

my `env.prod` file is below:

```
API_URL = 'url-to-external-api-here'
```

my `package.json` file is below:

```json
 "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "android-dev": "export ENVFILE=.env.dev && react-native bundle --platform android --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && react-native run-android",
    "android-prod": "react-native run-android --variant release",
    "android-staging": "ENVFILE=.env.staging react-native run-android",
    "build-android-prod": "export ENVFILE=.env.prod && react-native bundle --platform android --dev true --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && cd android && ./gradlew assembleRelease && cd .."
  },
```

I followed the instructions from README file 

* I linked the dependency to platforms running `react-native link react-native-config` on console.
* I added exception to `proguard-rules.pro` file like this:

```
... 

# BuildConfig --- on final of file
-keep class com.my.package.BuildConfig { *; }
```

Proguard isn't enable in `android/app/build.gradle`:

```

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false
```

References:

https://github.com/luggit/react-native-config/issues/74

https://github.com/luggit/react-native-config/issues/40

https://github.com/luggit/react-native-config/issues/148

**Comment by jinxac** [comment]
@francisrod01 i was stuck in same issue sometime back. 

You have give variables with spaces in your file as 

`API_URL = 'url-to-external-api-here'`

Can you remove spaces and try out. Something like this?

API_URL='url-to-external-api-here'

**Comment by francisrod01** [comment]
Hi @jinxac , thank you for answer me!

I tried:

* API_URL='url-to-external-api'`
* `API_URL=url-to-external-api`

and nothing changed.

12-23 06:45:57.328  1984  2004 I ReactNativeJS: '___ -==  API_URL: ', undefined

**Comment by francisrod01** [comment]
@jinxac I discovered that the problem actually is in how I was calling the ENVFILE along with the execute command from the app.

I reading the project recommendations again on the npm.js website.

https://www.npmjs.com/package/react-native-config#different-environments


I made some changes to the package.json scripts:

```js
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "android-bundle-dev": "react-native bundle --platform android --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res",
    "android-bundle-prod": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res",
    "android-dev": "ENVFILE=.env.dev react-native run-android",
    "android-staging": "ENVFILE=.env.staging react-native run-android",
    "android-prod": "ENVFILE=.env.prod react-native run-android --variant release",
    "build-android-prod": "cd android && export ENVFILE=.env.prod && ./gradlew assembleRelease && cd .."
  },
```

where I realized that `android-prod` and `build-android-prod` do the same thing, so to compile the app, just run one of the `scripts` commands.
