### ISSUE TITLE
Docs - Advanced Android Setup

### ISSUE THREAD

**Issue by filiipake** [luggit/react-native-config#209]
![image](https://user-images.githubusercontent.com/23082632/34609174-bd349220-f202-11e7-888d-87e2269b82dd.png)

> Only work for me if i put mypackage without .xml
> Ex: resValue "string", "build_config_package", "com.filiipake.app"

> #32 on @stilllife00 comment

**Comment by caroaguilar** [comment]
What the doc means is that you have to add there the package name same as it is in the `AndroidManifest.xml`, you should only add the package name, that's why it only works without the xml because that's how it suppose to work.
