### ISSUE TITLE
[iOS] Possible to make env variables as User-Defined Setting

### ISSUE THREAD

**Issue by henrikra** [luggit/react-native-config#218]
Would it be possible that this library would make my variables in `.env` file as User-Defined Settings on iOS? This way I could for example user .env variables in my entitlements file on iOS.

**Comment by iyucef** [comment]
Any update about this issue?

**Comment by adrianocola** [comment]
@iyucef #349 makes that possible

**Comment by pedro** [comment]
:+1: #349 has been merged/released with `0.12`
