### ISSUE TITLE
react-native-web support

### ISSUE THREAD

**Issue by PeterKottas** [luggit/react-native-config#225]
Is there anybody who successfully tested this lib with react-native-web? I have a setup that supports react-native-config for mobile devices but unfortunately not the web released from the same code. I am not saying it's a big shocker cause this was obviously build before react-native-web but it feels like it's only a step from working everywhere. Hope somebody will be able to help with this. Cheers

**Comment by PeterKottas** [comment]
Well as usual, right after publishing an issue, I found the solution. In case anybody comes across this go straight [here](https://github.com/tanhauhau/react-web-config) and follow the setup instructions.

**Comment by BayCo** [comment]
> Well as usual, right after publishing an issue, I found the solution. In case anybody comes across this go straight [here](https://github.com/tanhauhau/react-web-config) and follow the setup instructions.

Hey, @PeterKottas , i am running the same issue, it seems like installation of react-web-config is wrong, do you use this react-web-config now, how can i install it with react-app-rewired?

**Comment by varungupta85** [comment]
I am also running into this issue. It is not clear if `react-web-config` will work with `create-react-app` or `react-app-rewired`. Please share if anyone has a solution for this issue.

**Comment by theInfiTualEr** [comment]
I set up `react-native-config` for `react-native-web` with `expo` by following these steps: (although I'm not sure about the 3rd step, but it works for me)

1. follow this link: https://docs.expo.dev/guides/customizing-webpack/

2. install this library: https://github.com/tanhauhau/react-web-config

3. in your `webpack.config.js` file (which was created in step 1), add the following code:

```javascript

// log config.plugins and find index of DefinePlugin
config.plugins[4].definitions = {
  ...config.plugins[4].definitions,
  ...ReactWebConfig(envFilePath).definitions,
};
config.resolve.alias["react-native-config"] = "react-web-config";
```
