### ISSUE TITLE
can we change env variable dynamically?

### ISSUE THREAD

**Issue by ccoeder** [luggit/react-native-config#226]
Hi, thank you for this beautiful package, it has helped me a lot.

Is it possible to change the value of the variable in the .env file? Like:

```
Config.API_URL // 'https://myapi.com'
Config.API_URL = 'https://test.com'
Config.API_URL // 'https://test.com'
```

**Comment by pedro** [comment]
For sure! You can comment it out adding a `#` to the beginning of the line, like:

```
# Config.API_URL = 'https://myapi.com'
Config.API_URL = 'https://test.com'
```

**Comment by pedro** [comment]
Is this what you were looking for?

**Comment by ccoeder** [comment]
@pedro, can you help me with this?

**Comment by nilaybrahmbhatt** [comment]
@ccoeder  i m searching for the same.

**Comment by cbrwizard** [comment]
Just write `Config.API_URL = this.props.settings.API_URL`, it works.

**Comment by joaovpmamede** [comment]
@cbrwizard works on development not when building the app for "prod".
Correct?

**Comment by nriccar** [comment]
bump
