### ISSUE TITLE
Nodejs support for testing

### ISSUE THREAD

**Issue by shinout** [luggit/react-native-config#24]
We've just created a small library to mock this in Nodejs.

https://github.com/CureApp/react-native-config-node

Do you have an idea of merging the project?

**Comment by pedro** [comment]
Hey there!

So sorry for the delay, I'd definitely be down to merge this in to make sure this behaves well with test. Would you be willing to make a stab at a pull request?

Thanks!

**Comment by m-vdb** [comment]
I've been able to use this module when testing with mocha by 'simply' adding the following to a file that I require to run tests:
```javascript
import { NativeModules } from 'react-native';

// http://stackoverflow.com/a/35045012/999076
require('babel-core/register')({
  ignore: '/node_modules/(?!Project)/'
});

NativeModules.ReactNativeConfig = {};
```

**Comment by phillbaker** [comment]
Another alternative, for just mocking the `Config.FOO` usage:

```
# __mocks__/react-native-config.js
export default {
  FOO_BAR: 'baz',
};
```

**Comment by pedro** [comment]
Closing for now, still open to ideas merging react-native-config-node or just making testing easier here!

**Comment by dimitridewit** [comment]
@phillbaker thank you ! works for me :-)

**Comment by packmann** [comment]
> I've been able to use this module when testing with mocha by 'simply' adding the following to a file that I require to run tests:
> 
> ```js
> import { NativeModules } from 'react-native';
> 
> // http://stackoverflow.com/a/35045012/999076
> require('babel-core/register')({
>   ignore: '/node_modules/(?!Project)/'
> });
> 
> NativeModules.ReactNativeConfig = {};
> ```

jest.doMock('react-native', () => {
    // Extend ReactNative
    const ReactNative = require.requireActual('react-native');
    return Object.setPrototypeOf(
        {
            // Redefine an export, like a component
            NativeModules: {
                ...ReactNative.NativeModules,
                ReactNativeConfig: {
                    ENV: 'production',
                }
            },
Jest -^24.9.0  
Works like charm

**Comment by wolfag** [comment]
> ```js
> http://stackoverflow.com/a/35045012/999076
> ```

anyone can confirm will still work?. I tried on my project but not luck

**Comment by wolfag** [comment]
> Another alternative, for just mocking the `Config.FOO` usage:
> 
> ```
> // __mocks__/react-native-config.js
> export default {
>   FOO_BAR: 'baz',
> };
> ```

anyone can confirm will still work?. I tried on my project but not luck
