### ISSUE TITLE
Android from console missing .env

### ISSUE THREAD

**Issue by caroaguilar** [luggit/react-native-config#242]
Hi,

I already did all the setup and linking of the react-native-config. However I cannot find the variables I defined in my `.env` when I run the project using `react-native run-android`.
 If I print the config object I'm seeing this:

`{"FLAVOR":"","DEBUG":true,"VERSION_CODE":1,"BUILD_TYPE":"debug","APPLICATION_ID":"myappid","VERSION_NAME":"0.1.0"}` 

and none of my defined variables are shown.

In the logs I'm seeing

`**************************
*** Missing .env file ****
**************************`

When I run the project from Android Studio it works fine,  and all the variables are filled.

I'm using react-native 0.54.2 and react-native-config 0.11.5.

iOS works fine.

I would really appreciate the help with this.

Thanks!

**Comment by caroaguilar** [comment]
Hey I was able to fix it by opening the project in Android Studio, cleaning and build!

Thanks!

**Comment by maulikdhameliya** [comment]
you need to add defaultEnvFile property

check here https://stackoverflow.com/questions/49140463/missing-env-files-when-i-use-react-native-config-for-android/60299691#60299691
