### ISSUE TITLE
Android is not reading the content of env file

### ISSUE THREAD

**Issue by djalmaaraujo** [luggit/react-native-config#244]
It's working with IOS, and no error is showing when building the app, but when I open the app, it's not reading at all.

Known bug? Using the latest version `0.11.5` I get undefined for all values I try to read using: 

```js
import EnvConfig from 'react-native-config'
console.log(EnvConfig.API_URL) // undefined
```

env file:

```bash
GOOGLE_MAPS_API_KEY='XYZ'
API_URL='https://app.myapp.com.br/api'
```

**Comment by gabrielvcbessa** [comment]
Same problem here

**Comment by djalmaaraujo** [comment]
Closing this issue. I downgraded to 0.8X and react-native to "0.51". While I don't think it's react-native version, I also found some duplication and Maybe I am wrong, but I think react-native-config must be the first module in dependencies


```
dependencies {
    compile project(':react-native-config')
```

and here: `APP/android/settings.gradle`

```
rootProject.name = 'PlaceCar'
include ':react-native-config'
project(':react-native-config').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-config/android')
```

**Comment by gabrielvcbessa** [comment]
@djalmaaraujo Djalma, maybe this will help you: https://github.com/luggit/react-native-config/issues/243#issuecomment-379349157

**Comment by sirwoetang** [comment]
I am gonna be that guy. 

Our issue was not any of the above, but rather that the bundle identifier did not match the package name.

**Comment by alextorn** [comment]
> I am gonna be that guy.
> 
> Our issue was not any of the above, but rather that the bundle identifier did not match the package name.

Same problem...
