### ISSUE TITLE
Does not work for Android

### ISSUE THREAD

**Issue by RyanMitchellWilson** [luggit/react-native-config#25]
This works just fine on IOS but does not work for Android. I've doubled checked I have everything in the correct files, but when I run `react-native run-android` it fails to compile and I get this error: 
`error: method does not override or implement a method from a supertype
    @Override`

And when I remove `@Override` from the function it compiles and loads the app onto the emulator, but then all I get is `Cannot read property 'URL' of undefined` or `undefined is not an object (evaluating '_reactNativeConfig2.default.URL')`

Running React-native 0.29.0 and Java 1.8 Oracle

**Comment by RyanMitchellWilson** [comment]
Ok figured out the problem. Starting in React-Native 0.29.0 (https://github.com/facebook/react-native/releases/tag/v0.29.0) they added a new file inside the same folder as MainActivity.java called MainApplication.java where they want you to add your customizations. So instead of adding 

    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new ReactNativeConfigPackage() // add package
        );
    }

To your MainActivity.java you need to add it to MainApplication.java

**Comment by RyanMitchellWilson** [comment]
Tried to create a pull request for this but I don't have permissions to push a new branch.

**Comment by perkola** [comment]
Bump. Can you PR this into the master branch?

**Comment by pedro** [comment]
Done! Sorry for the delay, and thanks for the feedback folks.
