### ISSUE TITLE
Module ReactNativeConfig requires main queue setup

### ISSUE THREAD

**Issue by jackcbrown89** [luggit/react-native-config#250]
I saw that this was fixed in an earlier pull request, but I'm using `react-native-config@0.11.5` and `react-native: 0.55.3`. Here's the full stacktrace and error:
<img width="363" alt="screen" src="https://user-images.githubusercontent.com/5186405/39356467-5b162994-4a10-11e8-8f18-97041450f8c3.png">

**Comment by stefanuswendy** [comment]
i got the same issue. any update?

**Comment by jackcbrown89** [comment]
I eventually just used `YellowBox.ignoreWarnings(...);` and eventually updated a few things but never pinpointed the issue but just now I checked and it's gone. What version are you using?

**Comment by stefanuswendy** [comment]
"react": "16.3.1",
"react-native": "0.55.4",
"react-native-config": "^0.6.1",

i still having the issue.
