### ISSUE TITLE
Has any ability in android to export CUSTOMENV from .env to node without call it in commandline every time?

### ISSUE THREAD

**Issue by Dimon70007** [luggit/react-native-config#272]
Hi. Thank you very much for greate library.
In my app i need to specify env like below.
`CUSTOMENV=ENV1 node scripts/start.js`.
How i should do this with react-native-config? Has any ability in android to export `CUSTOMENV` from .env to node without call it in commandline every time?
It would be greate to spicify only ENVFILE and then android put other var to node from it. I tryed to set it in android/app/build.gradle like
```  
def envName = project.env.get("CUSTOMENV")
project.ext.react = [
    nodeExecutableAndArgs : ["CUSTOMENV=$envName node"],
]
```
 but unsuccessfully it has caused crash

**Comment by cf-bosung90** [comment]
First of all, please change the title to reflect the issue

There is PR that hopefully resolve your issue but I am not sure if this library is being maintained anymore.
https://github.com/luggit/react-native-config/pull/284

**Comment by mrozbarry** [comment]
Also, see #271 for the relevant issue, this is a duplicate.

**Comment by pedro** [comment]
👌 Closing in favor of #271, will follow up there.
