### ISSUE TITLE
.ENV is not compiled

### ISSUE THREAD

**Issue by SirPhemmiey** [luggit/react-native-config#276]
After bundling my release version, i discovered that the environment variables (.env, .env.production, .env.staging) were not linked (bundled) with the APK, hence causing some kind of errors (NETWORK FAILED).
I "googled" but all those stuffs didn't work out. So i went back to the README.md and went through it carefully. I went exactly to the Troubleshooting section and guessed the issue was with proguard.  I just added `-keep class com.mypackage.BuildConfig { *; }`
`mypackage `should match the package value in your a`pp/src/main/AndroidManifest.xml` file.

Good Luck!

**Comment by DavidNorena** [comment]
I think this is an issue tracker, but it will be very helpfull if you post it in stackoverflow :D a lot of people go there if they have problems :D
