### ISSUE TITLE
Compatibility with Android Build Variant Flavors

### ISSUE THREAD

**Issue by JeremyBradshaw7** [luggit/react-native-config#278]
This package was working nicely until I split my Android configuration across multiple Build Variant Flavors (see https://developer.android.com/studio/build/build-variants) - is there any reason this should stop it picking up environment values from the .env files? If so is there anything that can be done?

**Comment by JeremyBradshaw7** [comment]
https://github.com/luggit/react-native-config/pull/180 seems related, but I'm unclear how it should help me - it's merged almost a year ago but I'm still having the issue. Does it imply I have to have some .env fallback file?

**Comment by JeremyBradshaw7** [comment]
Closed, because this is addressed by the note under the Advanced Android Setup section:
https://github.com/luggit/react-native-config#advanced-android-setup

**Comment by shilu-stha** [comment]
@JeremyBradshaw7 that worked for me 👍
