### ISSUE TITLE
Using react-native-config with fastlane

### ISSUE THREAD

**Issue by sonlexqt** [luggit/react-native-config#298]
Hi, currently in my react-native app I configure two lanes using [`fastlane`](https://github.com/fastlane/fastlane): `beta` and `production`. I'm using [`react-native-config`](https://github.com/luggit/react-native-config) for different environment configs (stored in 2 files: `.env.beta` and `.env.production`). How can I let `fastlane` know which env file should be used for each lane ?

**Comment by drewandre** [comment]
If you follow the instructions under the [iOS section](https://github.com/luggit/react-native-config#ios-1) in the readme, you should be able to specify that scheme when using fastlane's [gym](https://docs.fastlane.tools/actions/gym/) like so:

`gym(
      scheme: '<APP_NAME_HERE> Staging',
      export_method: 'app-store',
      ...
)`

Similarly for android, assuming you've done everything under the [android](https://github.com/luggit/react-native-config#android-1) section in the readme, you should be able to run whatever `build_type` you want:

`gradle(
      project_dir: 'android',
      task: 'clean assemble',
      build_type: 'debug',
)`

**Comment by drewandre** [comment]
@sonlexqt my comment above actually isn't totally accurate. gradle's `build_type` needs to be capitalized, even though your actual build_type may be lowercase. so your gradle command for your android lane would be `gradle( project_dir: 'android', task: 'clean assemble', build_type: 'Debug' ... )`, and `gradle( project_dir: 'android', task: 'clean assemble', build_type: 'Release' ... )`, assuming you have configured your project's envConfigFiles as such:

    project.ext.envConfigFiles = [
        debug: ".env.development",
        release: ".env.production",
    ]

**Comment by cmcaboy** [comment]
For Android, you can specify an environment file in the gradle section:

`desc "Deploy a new alpha version to the Google Play Store"
  lane :alpha do
    version_code = increment_version_code(
      gradle_file_path: "./app/build.gradle"
    )

    gradle(
      task: "assembleRelease",
      system_properties: {
        **"ENVFILE": "/Users/jonathanmcaboy/Desktop/Dev/Tagg/.env.prod"**
      }
    )

    supply(
      track: "alpha",
      apk: "#{lane_context[SharedValues:: GRADLE_APK_OUTPUT_PATH]}"
    )

    git_commit(
      path: "./app/build.gradle",
      message: "Fastlane Android: Released new build #{version_code} [ci skip]"
    )
  end`

**Comment by aperomingo** [comment]
Giving next error with that config @cmcaboy 

```
[14:07:30]:  => 118:              system_properties: {
[14:07:30]:     119:                "ENVFILE": "/Users/<username>/Documents/GitHub/<project-name>/.env" + options[:env]
[14:07:30]:     120:              }
```

```
[!] Syntax error in your Fastfile on line 118: Fastfile:118: syntax error, unexpected ':', expecting end
          system_properties: {
```

**Comment by kubanac95** [comment]
I was initially going with the proposed solution found [here](https://github.com/fastlane/fastlane/issues/13494).

After having more than a few environments this because a bit of PITA to maintain, creating `.env ` files inside the app `fastlane` folder

What I settled with in the end is overriding the process of loading the environment files

```
fastlane_require 'dotenv'

default_platform(:android)

before_all do |lane|
  environment = lane_context[SharedValues::ENVIRONMENT]
  unless environment.nil?
      puts "Loading variables from env.#{environment}"

      Dotenv.overload '../.env.' + environment

      # Make sure react-native-config gets proper .env file loaded
      ENV["ENVFILE"] = ".env.#{environment}"
  end
end

platform :android do
  desc "Publish build"
  lane :publish do
    gradle(
      task: 'clean',
      project_dir: 'android/',
    )

    gradle(
      task: 'bundle',
      build_type: 'release',
      print_command: true,
      project_dir: 'android/',
    )
    upload_to_play_store(
      track: 'production',
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
```

What this does is check for the env file inside the project directory instead of fastlane folder. 

- Running `Dotenv.overload` will set env variables making them accessible in the lane itself. Like for .eg `ENV["BUGSNAG_API_KEY"]`
- Setting `ENV["ENVFILE"] = ".env.#{environment}"` will ensure `react-native-config` loads propper .env file from the root of the project when  building the project

Usage in the end

`fastlane android publish --env release`
