### ISSUE TITLE
Worked initially for Android, now Config is always empty

### ISSUE THREAD

**Issue by jacksonkr** [luggit/react-native-config#304]
**Specs**

**Android** 6 (v23) w **build-tools** 28
**OSX 10.14 / Windows 10** (have access to both)
**react-native-cli**: 2.0.1
**react-native**: 0.55.4
**npm** 6.4.1
**react-native-config**@0.11.5 

the `.env` variables show up in the **buildConfig.java** but not in the Config variable.

**The Setup**

.env
```
MY_URL=https://myapi.com
MY_KEY=new build test
```

app.js
```
import Config from 'react-native-config';
...
console.log(Config); // now only shows { }
```

app/build.gradle
```
project.ext.envConfigFiles = [
        debug: ".env",
        release: ".env",
        anothercustombuild: ".env",
]

apply plugin: "com.android.application"
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
...
defaultConfig {
        applicationId "com.workingproject"
        ...
}
...
dependencies {
        implementation project(':react-native-config')
        ...
}
...
```

I've also tried to `unlink` and re `link` a number of times with no success. Everything still works fine with iOS.

**Question**

How can I resolve?

**Comment by alvinwang19** [comment]
In the readme (https://github.com/luggit/react-native-config#extra-step-for-android), there is an extra step for android. Make sure you've done this and try again?

Extra step for Android
You'll also need to manually apply a plugin to your app, from android/app/build.gradle:

// 2nd line, add a new apply:
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

**Comment by jacksonkr** [comment]
A friend on the repo changed the compile SDK which caused the build process to break. Then when they changed the compile SDK back then the Config started working again. For the life of me I can't figure out what happened.

**Comment by onkarjanwa** [comment]
Hey,

I am facing the same issue, exact same. What should i do?

Thanks

**Comment by Sathyanarayan09** [comment]
I'm facing the same issue too

**Comment by wamry** [comment]
same here

**Comment by mengheangrat** [comment]
**I fixed this issue by added this to app/build.gradle**
 defaultConfig {
        resValue "string", "build_config_package", "com.yourpackage"  
    }

**Comment by lekeCoder** [comment]
@mengheangrat please can you briefly what this code snippet implies? Should l copy and paste your code and replace `com.yourpackage` with my package name?

**Comment by lekeCoder** [comment]
Thanks to @jacksonkr for his answer. this is the changes l made in my **`app/build.gradle`** 

```
project.ext.envConfigFiles = [
  debug: ".env",
  release: ".env"
]

apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
```
This did it.
