### ISSUE TITLE
RN 57 support with Babel Preset...

### ISSUE THREAD

**Issue by dbarner1** [luggit/react-native-config#322]
Hi,

First, love this.

Second, looks like upgrading to RN 57 broke this.  I found adding the required preset `"module:metro-react-native-babel-preset"` made the config variables return as undefined.

I don't have a solution here, but curious if others have found this, and if there is a solution out there.

Thank you!
Dave

**Comment by skrywus** [comment]
Have the same after upgrade to 0.57

**Comment by Marcsimm** [comment]
Have the same problem in RN 0.57.5.

**Comment by ivanzhang** [comment]
same in RN 0.57.8， need to check this source code to find out why return undefined , or config = {}

**Comment by ryands** [comment]
It seems fine for Android builds, only my iOS builds seem to be missing config data.

**Comment by dengue8830** [comment]
it works for android only, it does not work for JS, it returns an empty `{}` when i write `console.log('config', Config);`

**Comment by dengue8830** [comment]
fixed adding the line in `defaultConfig` 

https://github.com/luggit/react-native-config/issues/143#issuecomment-447579204

**Comment by ryands** [comment]
> fixed adding the `resValue` line in `defaultConfig`
> 
> [#143 (comment)](https://github.com/luggit/react-native-config/issues/143#issuecomment-447579204)

That's probably why I was having success on Android. I have that resValue set already for other reasons.  iOS is still broken and I haven't found a workaround at the moment.

**Comment by TingAli** [comment]
Still an issue it seems....

**Comment by TingAli** [comment]
(For Android, please can someone test this for iOS)
Fixed it by doing the following:

In the Android src folder, open the file "MainApplication.java" and do the following...

Add the following at the top:
`import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;`

In the "getPackages" function, add the following as part of the ArrayList:
`new ReactNativeConfigPackage()`

**Comment by andreyslyusar** [comment]
Does anybody manage to solve an issue with iOS and React-Native 0.57?

**Comment by ryands** [comment]
I ended up getting iOS to work again (we'd upgraded RN versions when the problem began) by manually going through the linking process.  YMMV though.

**Comment by dbarner1** [comment]
This worked! https://github.com/luggit/react-native-config/issues/322#issuecomment-452813041

Going to close the issue, as I think its solved. Feel free to re-open if you disagree.  :)
