### ISSUE TITLE
IOS build fails

### ISSUE THREAD

**Issue by jeanpaulgorman** [luggit/react-native-config#33]
Each time I try to build the app with this module installed I get the following error 
![screen shot 2016-09-14 at 13 09 03](https://cloud.githubusercontent.com/assets/8036382/18511618/9779126c-7a7c-11e6-8da0-70e0ef76274c.png)

**Comment by jeanpaulgorman** [comment]
Ahh ok the reason it fails was because my .env files have values that were in double quotes e.g.

MY_URL="https://thing.domain.com"

Where as it only works without the double quotes.

I'd guess some parsing of the .env contents is required.

I think that the fact that the DOT_ENV var is being generated by Ruby to make it available to the ReactNativeConfig.m is the reason the error manifests as a syntax error in the build phase.

**Comment by eschapp** [comment]
I had this exact same error. Moving from "key" to 'key' also solved the issue for me.

**Comment by pedro** [comment]
Latest version should work well with single or double quotes! Thanks folks :+1:
