### ISSUE TITLE
Android - Config not applied in Debug mode

### ISSUE THREAD

**Issue by atomheartother** [luggit/react-native-config#339]
## Specs
Since I feel this might be relevant as it's possible a package update broke it
```
Linux: 5.0.2
Distro: Arch Linux
```

## The bug
When building in **Debug**, android doesn't receive the config set in my custom file. It works fine in Release. To be more precise, I've put some print statements in `react-native-config`'s `dotenv.gradle` file during build to try and track this bug myself:
- My custom `.env.development` file is found
- It is read properly, the properties it reads are right, so the bug occurs either at or after this line:
`project.ext.set("env", env)`

## Notes
- The config used to work fine, it's possible it's due to a local change on my machine, other developers on this project aren't having this issue. I just don't see what it could be.
- This isn't specific to my phone, i've tried different ones, it is the machine.
- My applicationId is the same as the package name in the manifest.

## What I've tried
- Unlink/relink `react-native-config`
- Clone my project and reinstall everything
- Update `react-native-config` to the latest version
- Use different names for my .env file, even setting it through the ENVFILE env variable.
- Open the project in Android Studio and clean build

**Comment by wojteg1337** [comment]
hello@atomheartother,
which version of RN do you use?

**Comment by atomheartother** [comment]
Hey, I'm using RN version `0.57.4`.

I should mention this got fixed by retrying the "clone the repository and reinstall" option with some minor changes to gradle version in `distributionUrl` of `gradle-wrapper,properties`... Not sure if that's what fixed it but anyway, I can't reproduce this bug anymore.
