### ISSUE TITLE
[iOS] Cause build to purposefully fail if .env missing

### ISSUE THREAD

**Issue by arosendorff** [luggit/react-native-config#343]
Is it at all possible for react-native-config to cause the iOS build to fail if the .env file is missing? We sometime have the case where a new developer will not get the .env file, and wastes time with lengthy builds before finding out their error.

I don't know if it is possible, but if the build failed early on with a message about the missing file, it would be extremely useful.

**Comment by namaxinan** [comment]
How about adding an script on Pre-action of your current schema, to check the availability of .env file
```
if [ ! -f .env ]; then
    echo ".env not found!"
fi
```

**Comment by arosendorff** [comment]
@namaxinan That solves it perfectly, thank you!

**Comment by spsaucier** [comment]
We're passing a ENV file directly for some builds, so I didn't want to exit if `.env` is missing. Instead, I've set it to warn if the `.env` file is missing, or to fail out if it _does_ exist but is missing one or more variables that exist in `.env.staging`.

```
configfile='.env'
stagingfile='.env.staging'
if [ -f ${configfile} ]; then
    missing=false
    while read -r line; do
        field="${line%%=*}"
        if [ ! -z "${field##*'='*}" ]; then
            match=false
            while read -r line2; do
                field2="${line2%%=*}"
                if [ "$field" == "$field2" ]; then
                    match=true
                fi
            done < "$configfile"
            if [ $match == false ]; then
                missing=true
                echo "ENV var $field missing"
            fi
        fi
    done < "$stagingfile"
    $missing && >&2 echo "ENV vars missing - ensure you have an updated .env file" && exit 1
else
    echo "Missing .env file -- copy from .env.staging"
fi
exit 0
```
