### ISSUE TITLE
[SOLVED] ERROR: No value has been specified for property 'manifestOutputDirectory'.

### ISSUE THREAD

**Issue by SobakaSlava** [luggit/react-native-config#345]
Hi all. I've installed `react-native config`, successfully linked it, added `apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"` line to the `app/build.gradle` and after that my Android Studio sync fails with `ERROR: No value has been specified for property 'manifestOutputDirectory'.`. I noticed that this happens only after updagrading gradle to `gradle:3.4.0` and gradle-service to `distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip`. Seems like `react-native-config` doesn't work with the latest gradle

**Comment by bbowman** [comment]
Seeing this in our own project too (we dont use react-native though). Our errors is:
```
* What went wrong:
A problem was found with the configuration of task ':*******:processDebugAndroidTestManifest'.
> No value has been specified for property 'manifestOutputDirectory'.
``` 

when upgrading to plugin 3.4 /gradle 5.1.1 ... wondering if its an issue with the android plugin. Tried Andoird studio 3.5 and the issue went away so maybe just avoid plugin version 3.4 till they patch it.

**Comment by piotrdz** [comment]
I came across this problem in unrelated project, but I found a solution that works for me: disabling Gradle feature "Only sync the active variant". In Android Studio: File > Settings > Experimental > Gradle -> uncheck "Only sync the active variant" checkbox.

**Comment by Ke4nuReeves** [comment]
@piotrdz Thanks, it works or me too!

**Comment by rochapablo** [comment]
@piotrdz, sorry, but `Android Studio: File > Settings`? I only have `File > Others Settings` and `File > Settings Repository` and none of them have `Experimental > Gradle`.

**Comment by piotrdz** [comment]
@rochapablo Are you using macOS? On Mac the settings are under Android Studio -> Preferences.

**Comment by rochapablo** [comment]
@piotrdz, yes, I'm using macOS. Founded! thank you.

You know, **it did work**, but it seems that the error occurs only when you click in Sync (after some change on build.gradle). Even having the error, cleaning the project and rebuilding the error does not happen.

I don't know why this, [here](https://github.com/geektimecoil/react-native-onesignal/issues/639) I'm having a similar problem. When I Sync I got the error but cleaning and rebuilding the error goes way. But since it's another project, in this case I still have to try the `Only sync the active variant` option.

Anyway, thank you again for your time.

**Comment by SobakaSlava** [comment]
> I came across this problem in unrelated project, but I found a solution that works for me: disabling Gradle feature "Only sync the active variant". In Android Studio: File > Settings > Experimental > Gradle -> uncheck "Only sync the active variant" checkbox.

As long as it seems to be the solution (checked in a new project, it helps) I close the issue

**Comment by kapilkarda** [comment]
> @piotrdz, sorry, but `Android Studio: File > Settings`? I only have `File > Others Settings` and `File > Settings Repository` and none of them have `Experimental > Gradle`.

After doing that my bundle is not opening automatically from android studio.
can you please help me with that ?

**Comment by valabji** [comment]
> I came across this problem in unrelated project, but I found a solution that works for me: disabling Gradle feature "Only sync the active variant". In Android Studio: File > Settings > Experimental > Gradle -> uncheck "Only sync the active variant" checkbox.

Thanks Dude, you saved my day
