### ISSUE TITLE
Question: Dynamic Entitlements from react-native-config?

### ISSUE THREAD

**Issue by evanjmg** [luggit/react-native-config#352]
Is it possible to configure associated domains via react native config? It uses an entitlements file? Could we preprocess that?

**Comment by maxkomarychev** [comment]
@evanjmg this tool doesn't offer special support for that.
However, this PR https://github.com/luggit/react-native-config/pull/349 exposes rnconfig values to build settings, where you can select one or the other entitlements file.

**Comment by evanjmg** [comment]
Thanks, will give that try and it makes sense

**Comment by Achilles0509** [comment]
I tried to use environment variable in `entitlements` file, but it seems do not work.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>development</string>
	<key>com.apple.developer.associated-domains</key>
	<array>
		<string>applinks:$(APPLINKS)</string>
	</array>
</dict>
</plist>
```

Has someone experience with that?

**Comment by Adnan-Bacic** [comment]
still no update/solution for this?
