### ISSUE TITLE
Cannot read from env in Info.plist but it works in js code. Someone helps me?

### ISSUE THREAD

**Issue by suupham2506** [luggit/react-native-config#362]
React native: 0.60.3
Platform: IOS.
I cannot read env in Info.plist with __RN_CONFIG_.... anymore.
Could anyone help me set up this module in the right way on IOS.

**Comment by Maxwell2022** [comment]
@suupham2506 how did you fix it? the doc is not talking about the prefix `_RN_CONFIG_` so I'm not sure you need it anymore. However, I still cannot use it in my `info.plist`, I'm trying to change the bundle id per env
