### ISSUE TITLE
[Closed]

### ISSUE THREAD

**Issue by JakeRawr** [luggit/react-native-config#368]
Hi, 

I used this library for my aws credentials, but google play console alerted me that I have exposing my aws credentials from <app>.BuildConfig class

Any ideas?

**Comment by leethree** [comment]
From README:

> Keep in mind this module doesn't obfuscate or encrypt secrets for packaging, so do not store sensitive keys in .env. It's basically impossible to prevent users from reverse engineering mobile app secrets, so design your app (and APIs) with that in mind.

Google is correct. You shouldn't save your AWS credentials in your app code.

**Comment by JakeRawr** [comment]
Thanks!
