### ISSUE TITLE
Update docs to include usage of react-native-config-node

### ISSUE THREAD

**Issue by mguay22** [luggit/react-native-config#369]
This nice little mock allows users to run react-native-config in tests like Jest or Mocha exactly as it would during normal usage. It would be nice to include a mention about this, as configuring Jest with react-native-config was not very intuitive until I stumbled upon it.

https://github.com/CureApp/react-native-config-node

**Comment by Noitham** [comment]
Should this be removed?
The package `react-native-config-node` is archived.
