### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by leethree** [luggit/react-native-config#375]
The latest iOS change is merged but no new version is released. This causes huge confusion because the README doesn't match the latest version on NPM.

No maintainer is actively responding to issues and PRs for more than a year. See #269

Can anyone suggest a good fork with responsible maintainers? Or any other library with similar functionalities?

**Comment by dbarner1** [comment]
I sadly agree with this :(

**Comment by conor909** [comment]
Are there any alternatives that gives us env vars in both native and js code?

**Comment by pedro** [comment]
Hey folks! Sorry for the trouble, we're working to have this migrated to react-native-community.
Follow #382 for updates.

**Comment by leethree** [comment]
@pedro Thanks for the update! This project has been very useful to us and we hope it can find a new home soon!
