### ISSUE TITLE
How can I tell react-native what .env file to look at?

### ISSUE THREAD

**Issue by LuizFBrisighello** [luggit/react-native-config#378]
Lets talk android here.

On windows, i'm developing a white label app and I'm trying to use env variables to make code specific builds. I followed the Readme setup, but for some reason `SET ENVFILE=.env.mycustomenvironment` doesn't do anything for me, even with a defined map in build.gradle like this:

```
project.ext.envConfigFiles = [

debug: ".env",

release: ".env",

mycustomenvironment: ".env.mycustomenvironment",

]
```

Any ideas?

If there is a way to change the value of a .env var from command line when building, that would help too, .e.g `some-kind-of-parameter react-native -run-android`

**Comment by dmongit** [comment]
Did you solve this? I have the same problem.
