### ISSUE TITLE
ENVFILE doesn't work in React Native 0.59.10

### ISSUE THREAD

**Issue by kelokchan** [luggit/react-native-config#379]
I have this npm script `ENVFILE=.env.prod react Native run-ios` setup but it doesn't work at all. It always read the env variable from `.env` instead. 

It works fine if I build in xcode though as I have setup the Pre-build action. 

Not sure what's happening here at it used to work fine in previous versions (RN0.52.2 react-native-config0.8.1)

**Comment by LuizFBrisighello** [comment]
Same issue here on 0.60+
Im on windows deving for android and `SET ENVFILE=.env.mycustomenvironment` doesnt do anything.

**Comment by beeremy** [comment]
Same issue here. It seems that the env file is not read after upgrading from 0.53 to 0.59.10. 

Have you found a solution?

**Comment by LuizFBrisighello** [comment]
@beeremy Nothing ideal yet. What im doing is using `react-native-config` to be able to tell RN which .env file to look at with `$env:ENVFILE=".env.mycustomenv"` _(using powershell on windows)_
And to expose those variables to my JS im using `react-native-build-config`.

**Comment by LuizFBrisighello** [comment]
@beeremy I was trying to pass `SET ENVFILE=.env.mycustomenvironment` on vscode integrated terminal and nothing happened. What worked was using `powershell` nad passing the command like this `$env:ENVFILE=".env.mycustomenvironment"`

**Comment by kelokchan** [comment]
Silly me, I have `ENVFILE=.env.sit` but I also have a pre-built script `echo '.env'; /tmp/envfile` setup so I assume the pre-built script has overwritten my former command.

**Comment by subashtimalsina** [comment]
I also encountered the same issue if any of you guys have the solution please share with me, or any other alternative ideas are warmly welcome. Thank You!

**Comment by mengheangrat** [comment]
**I fixed this issue by added this to app/build.gradle**
 defaultConfig {
        resValue "string", "build_config_package", "com.yourpackage"  
    }

**Comment by dmongit** [comment]
> **I fixed this issue by added this to app/build.gradle**
> defaultConfig {
> resValue "string", "build_config_package", "com.yourpackage"
> }

I have this added already but still have the same problem.

**Comment by burhan3759** [comment]
Jun 2020, still have this issue. Initially it work fine, only break after add the Scheme

**Comment by ys-sherzad** [comment]
Any updates on this, it doesn't work for iOS
e.g.
```
ENVFILE=.env.Stage react-native run-ios
```
No effect whatsoever
