### ISSUE TITLE
There is no doc about how to use env variables in Info.plist or {Project}.entitlements

### ISSUE THREAD

**Issue by mav10** [luggit/react-native-config#387]
Guys, thanks for your package, everything is cool, but I didn't get anything according to the configuration of iOS project.

First thing - why in **readme** or whatever else there are no mentions about prefix which we should use in iOS proj? I mean ```__RN_CONFIG_```.  I found it by chance somewhere in issues.
- And by the way should i?

Second things is that -  i'm sorry but for me it's not clear how to configure xCode for getting env-variables in Info.plist. Yes you've got "**extra step**" how to do it, but i didn't get the main thing - it's a snippet in the last step. What should i do with that?

`"${SRCROOT}/../node_modules/react-native-config/ios/ReactNativeConfig/BuildXCConfig.rb" "${SRCROOT}/.." "${SRCROOT}/tmp.xcconfig"`

Could you provide an example, please?

And I'll ask one more time - but is it possible somehow to use a variable in the `{Project}.entitlements` for associated domains as in Info.plist.

**Comment by mav10** [comment]
found solution in #365

**Comment by sergiulucaci** [comment]
@mav10 but how are you using this solution to use env in `{Project.entitlements}`?

**Comment by pragneshpj** [comment]
how can i get **__RN_CONFIG_BundleVersion** in Info.plist?
can anyone help me

**Comment by luisfuertes** [comment]
@sergiulucaci @mav10 any update about this? how are you using this solution to use env in {Project.entitlements}?

**Comment by Adnan-Bacic** [comment]
still no update/solution for this?

**Comment by PierreCapo** [comment]
For `entitlements` fine, indeed you can do the same mechanic GoogleInfoServices for firebase:
1) Create one entitlement file per environment
2) In the scheme schema, add a pre-action build to copy the entitlement for the environment file to override the one used by your app 👍
