### ISSUE TITLE
Empty config when using Proguard

### ISSUE THREAD

**Issue by cjinghong** [luggit/react-native-config#388]
When running with `ENVFILE=.env.prod react-native run-android` works fine (Config includes the correct configuration specified inside .env.prod file). Building a release APK with `ENVFILE=.env.prod ./gradlew assembleRelease` works fine as well.

After using proguard, my Config starts to return empty object. Why is that? I've already tried to keep the classes of ReactNativeConfig by adding `-keep class com.lugg.ReactNativeConfig.** { *; }` to my proguard-rules.pro, but the same problem persist.

**Comment by Asdolo** [comment]
@cjinghong

Were you able to solve it?
