### ISSUE TITLE
Are Config Variables Cached?

### ISSUE THREAD

**Issue by joncursi** [luggit/react-native-config#39]
I set up an environment file with a Google Maps API Key and loaded it into android via ApplicationManifest.xml:

```
      <meta-data
       android:name="com.google.android.geo.API_KEY"
       android:value="@string/GOOGLE_MAPS_API_KEY"/>
```

When I started the android app via

```
ENVFILE=config/.env.development ./node_modules/.bin/react-native run-android
```

it worked. Out of curiosity, I changed the API key to a fake value, restarted the packager, restarted the emulator, and restarted the android app. It worked again, but it shouldn't have. Is something being cached? I want to make sure the right variables are getting loaded every time. Thanks!

**Comment by aroth** [comment]
I'm also running into this on both iOS & Android.

**Comment by 2ducanhpham** [comment]
@joncursi delete app and rebuild. Working for me

**Comment by pedro** [comment]
Odd, `run-android` should always reflect the latest environment.

Maybe you have the `applicationId` or there? In this case changing the ENVFILE could actually make Gradle compile a new app, and your previous one would keep working with the previous env.

Let me know if the issue persists!

Thanks,
