### ISSUE TITLE
Android not detecting .env file even when specified

### ISSUE THREAD

**Issue by codeithuman** [luggit/react-native-config#392]
I run the following command and my Android React Native app installs and launches but acts as if there is no .env file. 

```bash
ENVFILE=.env.staging react-native run-android           # bash
```

This command for `run-ios` works as expected. 

```
"react-native-config": "^0.11.7",
"react-native": "0.59.10",
```

**Comment by hlebon** [comment]
In **MainApplication.java** add the following line

`import com.lugg.ReactNativeConfig.ReactNativeConfigPackage`

and in getPackages method add:

```
return Arrays.<ReactPackage>asList(
          new ReactNativeConfigPackage(), // add this line
        // ... your packages
)
```

I hope it helps you, It worked for me.

**Comment by codeithuman** [comment]
That works @hlebon. Thank you so much!
