### ISSUE TITLE
Package not working on android release build only

### ISSUE THREAD

**Issue by schumannd** [luggit/react-native-config#396]
Using version: 0.11.7

When running

`ENVFILE=.env.production ./gradlew assembleRelease`

the logs say

`Reading env from: .env.production`

but the configs can't be imported / are empty. And this only happens on android relase build. debug is fine, and iOS is fine completely. This bug also came out of nowhere. Anybody else experiencing this? Tested with Android 8 and 9

**Comment by schumannd** [comment]
it was an issue with proguard. No clue why it popped up suddenly

**Comment by sadi304** [comment]
hello, how did you fix the issue?

**Comment by schumannd** [comment]
I stopped using this package.

**Comment by sadi304** [comment]
:v . Good decision to be honest. Setup was already complicated enough + no way I was able to make it work. Spent 3/4 hours doing this. Now decided not to use this plugin. Can't rely on this in production applications.

**Comment by ammichael** [comment]
what are the alten

> I stopped using this package.



> I stopped using this package.

what are you using now?

**Comment by ahmaddehnavi** [comment]
if you only have a problem with an android release build then make sure you ignore your.app.package.name.BuildConfig from proguard.
