### ISSUE TITLE
.env files do not accept integer values for params

### ISSUE THREAD

**Issue by ykeysergit** [luggit/react-native-config#415]
Exception thrown when running in Android: "String cannot be cast to java.lang.Double".

getDouble
ReadableNativeArray.java:91

extractArgument
JavaMethodWrapper.java:63

Example:
LOGGER_SEVERITY=DEBUG
LOGGER_BATCH_SIZE=50
LOGGER_CAPACITY=5000
LOGGER_FLUSH=3000

**Comment by PaulMest** [comment]
Almost all .env parsers assume that all values are strings. If you want to, you can cast a value from a string to an integer in your Java code.

```java
int loggerBatchSize = Integer.parseInt(env.LOGGER_BATCH_SIZE);
```

or in your JS code...

```js
const loggerBatchSize = parseInt(env.LOGGER_BATCH_SIZE, 10);
```

**Comment by ykeysergit** [comment]
Found the root cause is in a separate code base. Will close this ticket.
