### ISSUE TITLE
Not working while building release

### ISSUE THREAD

**Issue by sjsakib** [luggit/react-native-config#431]
I have these scripts to run and build the app:
```
"android": "ENVFILE=.env.development react-native run-android",
"ios": "ENVFILE=.env.development react-native run-ios",
"start": "ENVFILE=.env.development react-native start",
"apk": "cd android && ENVFILE=.env.development ./gradlew assembleRelease",
"aab": "cd android && ENVFILE=.env.production ./gradlew buildRelease",
```
Among them first the first three is working fine. But the ones involving `cd` is not not. I tried `ENVFILE=../.env.development`. That is not working either. I've also tried setting them in `android/app/build.gradle` 
```
project.ext.envConfigFiles = [
    debug: ".env.development",
    release: ".env.production",
]
```

**Comment by sjsakib** [comment]
Turns out it was Pro guard  issue.

**Comment by cmnstmntmn** [comment]
@sjsakib how did you solve this?
i open this issue [here](#479 ) that seems to address the same issue.

**Comment by AjayShivanagol** [comment]
any solution?

**Comment by dipeshkoirala21** [comment]
I am also facing the same issue. .env.staging's variables are working fine on debug mode, but its not working on release mode.Can somebody help me out here?

**Comment by bonnmh** [comment]
same problem

**Comment by amalmohann** [comment]
I'm also facing the same issue, when i checked the values by toasting, I got empty string for endpoints

**Comment by amalmohann** [comment]
Problems with Proguard
When Proguard is enabled (which it is by default for Android release builds), it can rename the BuildConfig Java class in the minification process and prevent React Native Config from referencing it. To avoid this, add an exception to `android/app/proguard-rules.pro:`

```
-keep class com.mypackage.BuildConfig { *; }
```

mypackage should match the package value in your `app/src/main/AndroidManifest.xml` file.

**Comment by patebry** [comment]
@amalmohann Thank You!
> ```
> -keep class com.mypackage.BuildConfig { *; }
> ```
> 
> mypackage should match the package value in your `app/src/main/AndroidManifest.xml` file.

This worked

**Comment by silviaphungky** [comment]
> Problems with Proguard When Proguard is enabled (which it is by default for Android release builds), it can rename the BuildConfig Java class in the minification process and prevent React Native Config from referencing it. To avoid this, add an exception to `android/app/proguard-rules.pro:`
> 
> ```
> -keep class com.mypackage.BuildConfig { *; }
> ```
> 
> mypackage should match the package value in your `app/src/main/AndroidManifest.xml` file.

I stuck in one day to trying figure out this issue. Your comment help me 🙇‍♀️🙇‍♀️🙇‍♀️🙇‍♀️
