### ISSUE TITLE
0.12.0 vs 1.0.0

### ISSUE THREAD

**Issue by jstheoriginal** [luggit/react-native-config#435]
There are no change logs that I can find/no release notes for 1.0.0. Is this a breaking change? Does it need any migration to prevent issues?

**Comment by luancurti** [comment]
> There are no change logs that I can find/no release notes for 1.0.0.

@jstheoriginal I release a `stable` version named as `1.0.0` why I've merged a lot of pull requests and I haven't had time yet to create a release notes, sorry about that. To be more clear with you I released `1.0.0` only why I consider this version `stable` and `updated`, but I have plans to migrate this package to `react-native-community` we are working in this and we will communicate is in this repository.

> Is this a breaking change?

No it isn't

> Does it need any migration to prevent issues?

No I've migrated in my app from `0.12` to `1.0.0` without problems

**Comment by jstheoriginal** [comment]
Sounds good! Thanks for confirming. 👍
