### ISSUE TITLE
[iOS] New Release after 0.1.0?

### ISSUE THREAD

**Issue by negativetwelve** [luggit/react-native-config#44]
Hi there,

This commit https://github.com/luggit/react-native-config/commit/085704a1a7f3580bf773f19f85a0914450db3a3f (already in master) fixes an issue we're having with custom directories for the .env files. Could you release a new version with this commit in it?

Thanks again for making this package!

**Comment by pedro** [comment]
Oops – you bet, just released 0.1.1! Thanks

**Comment by negativetwelve** [comment]
awesome, thanks!

**Comment by urska19** [comment]
Hi
Just wanted to say, that with this release stating environment for ios using `echo ".env.test.xcconfig" > /tmp/envfile` will result in missing file error, because custom env file is now expected in node_modules/react-native-config/ios/ and not above that directory.
