### ISSUE TITLE
Values not updating

### ISSUE THREAD

**Issue by zuffik** [luggit/react-native-config#464]
My `.env` file:

```
USE_STORYBOOK=false
```

When I change the value to `true` and restart watch, the `Config.USE_STORYBOOK` is still `'false'`. Output from `console.log(Config)`: `{"USE_STORYBOOK": "false"}`

**Comment by luancurti** [comment]
Did you used the `--reset-cache` option?

**Comment by zuffik** [comment]
Hi, thanks for quick response. Yes, I tried `--reset-cache` but it didn't help.

**Comment by zuffik** [comment]
Silly me, I'm sorry. I already have the `USE_STORYBOOK` variable within system environment variables (idk where it is defined but it's already set to `false`).
