### ISSUE TITLE
No signature of method: java.lang.Boolean.replaceAll() is applicable for argument types: (String, String) values: [%, \\u0025]

### ISSUE THREAD

**Issue by ManhVuTien** [luggit/react-native-config#474]
I have this issue when running android
![download](https://user-images.githubusercontent.com/30967592/87750398-8b061c00-c825-11ea-8ba8-7d3640b713b3.png)
I have researched but can't find any solution

**Comment by luancurti** [comment]
@ManhVuTien this problem occurs with the version `1.3.0` update to `1.3.1` to fix this problem
