### ISSUE TITLE
Add output file to the podspec

### ISSUE THREAD

**Issue by vidit-bhatia** [luggit/react-native-config#485]
I am trying to build my react native project which uses react native config on MS Appcenter.

It gives me an error 

`error: Build input file cannot be found: '/Users/runner/work/1/s/node_modules/react-native-config/ios/ReactNativeConfig/GeneratedDotEnv.m' (in target 'react-native-config' from project 'Pods')`

The reason it gives this error is that even though the ruby script is executed this file is not added to the xcode project as the output file is not marked for this to work we must update the pospec like the following

`output_files: ['$PODS_TARGET_SRCROOT/ios/ReactNativeConfig/GeneratedDotEnv.m']`
after the input line
`input_files: ['$PODS_TARGET_SRCROOT/ios/ReactNativeConfig/BuildDotenvConfig.rb'],`

**Comment by nol13** [comment]
Is this the same issue I'm seeing where we need to uninstall and then reinstall this library after every unrelated pod change, or appcenter will give this same error? Reinstalling react-native-config after other pod changes seems to be a workaround for now at least.

**Comment by billnbell** [comment]
https://github.com/luggit/react-native-config/pull/699

**Comment by luancurti** [comment]
Fixed in `1.4.12`

**Comment by adey69** [comment]
@luancurti the update (`1.4.12`) is working for me.
