### ISSUE TITLE
GeneratedInfoPlistDotEnv.h file not found in RN 0.63.2

### ISSUE THREAD

**Issue by lucipacurar** [luggit/react-native-config#489]
I'm trying to upgrade from `"react-native-config": "0.11.7"` to `"react-native-config": "1.3.3"` and I get one weird error. In the build output it says it generated the `GeneratedInfoPlistDotEnv.h`:
`Wrote to /Users/lucian/Library/Developer/Xcode/DerivedData/[REDACTED]/Build/Products/GeneratedInfoPlistDotEnv.h`
and when it tries to use it, it loads the file from another location: `<built-in>:1:10: fatal error: '/Users/lucian/work/app/ios/../node_modules/react-native-config/ios/ReactNativeConfig/GeneratedInfoPlistDotEnv.h' file not found`

Any idea how if it's a bug in react-native-config or the project config?

**Comment by lucipacurar** [comment]
Somehow I missed these steps:

```
### Extra step for iOS (support Info.plist)
* Go to your project -> Build Settings -> All
* Search for “preprocess”
* Set `Preprocess Info.plist File` to `Yes`
* Set `Info.plist Preprocessor Prefix File` to `${BUILD_DIR}/GeneratedInfoPlistDotEnv.h`
* Set `Info.plist Other Preprocessor Flags` to `-traditional`
* If you don’t see those settings, verify that “All” is selected at the top (instead of “Basic”)
```

**Comment by AnthonyTailer** [comment]
@lucipacurar I have the exactly same problem, i've tried these steps but they didn't work.
Please see my comment on [this issue](https://github.com/luggit/react-native-config/issues/496#issuecomment-702379931). Can you show us how did you solve this problem?

**Comment by lucipacurar** [comment]
<img width="679" alt="Screenshot 2020-10-02 at 15 57 42" src="https://user-images.githubusercontent.com/198549/94925641-37bc7500-04c8-11eb-94b1-9874ee8bd505.png">

This is all I set. Made sure I ran `npm install`, `pod install` inside the `ios` folder. And everything went just fine afterwards.
