### ISSUE TITLE
Support newest Android Gradle Plugin version 4.1.0

### ISSUE THREAD

**Issue by jihokim2** [luggit/react-native-config#507]
I met compile error like this. How can I fix it? 

/node_modules/react-native-config/android/dotenv.gradle' line: 83

* What went wrong:
Execution failed for task ':app:generateDebugBuildConfig'.
> No signature of method: com.android.build.gradle.internal.variant.ApplicationVariantData.getName() is applicable for argument types: () values: []
  Possible solutions: getAt(java.lang.String), getClass()

**Comment by jihokim2** [comment]
This issue happens 'com.android.tools.build:gradle:4.1.0' not 'com.android.tools.build:gradle:4.0.2'.

**Comment by lnk1729** [comment]
I have faced this issue as well. Seems pretty recent.

**Comment by anfriis** [comment]
@jihokim2 Can you change the issue title to be more descriptive e.g. 
"Support newest Android Gradle Plugin version 4.1.0" ?

**Comment by jihokim2** [comment]
I think 'Fix for gradle 4.1.0. #502's solution. Is it solution? @anfriis

**Comment by anfriis** [comment]
Yes that PR could be a solution to this issue. 
But I still think you should change the title of this issue to be more descriptive.

**Comment by jihokim2** [comment]
Sorry, I changed title of the issue. Thank you for this.

**Comment by jihokim2** [comment]
After I update react-native-config 1.4.0, this issue disappeared

**Comment by Mirjo** [comment]
@mrousavy If the issue still persists, try upgrading to 1.4.4. I blindly installed 1.3.3 from the copy-box on the npmjs-page and had the same issue.
