### ISSUE TITLE
Should warn users that API keys are not secure

### ISSUE THREAD

**Issue by brentvatne** [luggit/react-native-config#51]
You can use `apktool` to find the API keys for any Android app that uses this very easily. The README should probably warn users not to put any truly sensitive keys in here.

**Comment by pedro** [comment]
Good reminder :+1: will add that in.

But, to be clear, there's no real secure way to pack truly sensitive keys with any Android/iOS apps, right? To my knowledge the most you can is obfuscate, and surely there are ways to make the reverse engineering very hard – but still it seems like the only reasonable recommendation for mobile developers is to never package sensitive keys with their apps.

**Comment by brentvatne** [comment]
> but still it seems like the only reasonable recommendation for mobile developers is to never package sensitive keys with their apps.

yup!

**Comment by pedro** [comment]
:+1: thanks @brentvatne !
