### ISSUE TITLE
[iOS] .env.staging gets copied but i still have the .env.development vars

### ISSUE THREAD

**Issue by rares-lupascu** [luggit/react-native-config#511]
Hi

So I have done exactly what is written in the documentation
The vars are getting loaded but for some reason, it does not matter what the contents of the .env is, the development vars are always being served

I really do not know where to go from here :(

Thanks

**Comment by rares-lupascu** [comment]
so i solved it but changing the code that copies the env file to this code

```
if [ "${ENVFILE}" ]; then echo "${ENVFILE}" > /tmp/envfile ; else echo ".env.development" > /tmp/envfile; fi
```

**Comment by flogy** [comment]
Had the same issue but with Xcode schemas. Solved it using your approach by updating the `/tmp/envfile` in the pre-build action of every schema:

```
cp "${PROJECT_DIR}/../.env.production" "${PROJECT_DIR}/../.env"
echo ".env.production" > /tmp/envfile
```
