### ISSUE TITLE
Empty config object when enableProguardInReleaseBuilds is set to true.

### ISSUE THREAD

**Issue by loursbourg** [luggit/react-native-config#513]
Everything works fine when i run the app in debug mode, but when i build a release, i get an empty config object.
When i set enableProguardInReleaseBuilds to false, everything works fine.

**Comment by loursbourg** [comment]
I did not rtfm. : P

**Comment by navjotsing-dhanawat** [comment]
@loursbourg how did you solved this?

**Comment by loursbourg** [comment]
> @loursbourg how did you solved this?

Add this to your pro guard rules file:

`-keep class com.mypackage.BuildConfig { *; }
`
Don't forget to replace com.mypackage with your package name

**Comment by BinMansoor11** [comment]
> 

It must be added in documentation!
