### ISSUE TITLE
Values are undefined

### ISSUE THREAD

**Issue by akiladevinda** [luggit/react-native-config#521]
I installed react-native-config and added a .env file to the root of my project. This .env file contains the following:

```
API_URL=https://myapi.com
GOOGLE_MAPS_API_KEY=abcdefgh
```

Then I tested using console log

```
import Config from 'react-native-config';

console.log(Config.GOOGLE_MAPS_API_KEY) // undefined;
```

**Comment by VadimZP** [comment]
Same!

**Comment by VadimZP** [comment]
Okay! I've added **apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"** to _android\app\build.gradle_ and now it works. But it confused me cause autolinking was successful.

**Comment by catalinberta** [comment]
@VadimZP That fixed it for me. For some reason, the autolinking didn't kick in here

**Comment by rusakovic** [comment]
` <string moduleConfig="true" name="CodePushDeploymentKey">@string/CODEPUSH_ANDROID_KEY</string>`
Not working in Production. With plain string Codepush is working

But in debug  I could get the value `console.log(Config.CODEPUSH_ANDROID_KEY)`

"react-native": "0.64.2",
"react-native-config": "^1.4.2",

**Comment by sadeghhosseini** [comment]
Had the same problem. in this [step](https://github.com/luggit/react-native-config#advanced-android-setup) forgot to replace `YOUR_PACKAGE_NAME_IN_ANDROIDMANIFEST_XML` with the name of my package.
