### ISSUE TITLE
GeneratedInfoPlistDotEnv.h' file not found

### ISSUE THREAD

**Issue by piyush-bm-ai** [luggit/react-native-config#524]
I have tried multiple solutions available for this, but none work for me. I have recently upgraded from react 62 to 63, and react-native-config 1.2.0 to 1.3.3, and started facing this issue. Earlier everything worked for me. Even now, if i go back to that old branch, things work for me.

Also, for more context - **Running the app works for me, but archiving fails on XCode. In android, everything works well.**

What can be the issue?

Things I have tried (and they did not work) - 
1) adding post install scripts in podfile
2) manual linking
3) both 1 and 2 together
4) Changing info .plist preprocessor prefix file - and other changes there

Let me know if you need any other information.

**Comment by irfanrosly** [comment]
Also facing the same issue here.
react-native-config 1.4.1 and the then downgrade to 1.0.0 also the same.

**Comment by irfanrosly** [comment]
@piyush-bm-ai in my case `INFOPLIST_PREFIX_HEADER = "${BUILD_DIR}/GeneratedInfoPlistDotEnv.h";` is the culprit. Removing this line in `project.pbxproj` resolve the issue.

**Comment by uldh** [comment]
> @piyush-bm-ai in my case `INFOPLIST_PREFIX_HEADER = "${BUILD_DIR}/GeneratedInfoPlistDotEnv.h";` is the culprit. Removing this line in `project.pbxproj` resolve the issue.

This solution works, thanks.

**Comment by sanderwapstra** [comment]
This indeed works, but are there any consequences?
