### ISSUE TITLE
Bitrise compatibility with react-native-config

### ISSUE THREAD

**Issue by gelodgreat** [luggit/react-native-config#526]
When building through Bitrise the env is not getting read. I already tried setting ENVFILE=.env ahead of the build script

**Comment by TheSolly** [comment]
I am having the same issue; specifically when using a different `applicationIdSuffix` than the package name in the `AndroidManifest.xml`, although I've done the Android Advanced Setup step.

**Comment by TheSolly** [comment]
@gelodgreat I see you closed this issue, any solution?

**Comment by ArturV93** [comment]
# Add this script after npm/yarn install:

`echo "Suffix=$Suffix" >> $BITRISE_SOURCE_DIR/.env
cat $BITRISE_SOURCE_DIR/.env`

**Comment by ArturV93** [comment]
@elouisramseyc 
Did you add your env to Env Vars? Check in the Script step during the build—it should print assigned variables and values. If they aren’t, make sure they’re added in App Environment Variables or Workflow Environment Variables  so they’re accessible throughout the build

**Comment by jtvargas** [comment]
So, was the issue resolved by adding some Env Vars? @ArturV93 @gelodgreat
