### ISSUE TITLE
ios: config gets copied from .env.staging to .env on build

### ISSUE THREAD

**Issue by tareqdayya** [luggit/react-native-config#552]
Hi there,

I'm running:

"react-native-config": "^1.4.1",
"react-native": "0.63.3"

I have 2 env files: .env and .env.staging. They're not identical. And every time i try to build on ios, the contents of .env.staging, for some reason I can't understand, get copied to .env overwriting .env's values. In other words, .env becomes a copy of .env.staging and I end up with that config.

This problem is not present on Android.

My build is a debug build.

Any idea what's going on? I checked xcode, but it doesn't seem i'm importing any env variables in the schema configuration.

**Comment by JCameronP** [comment]
Did you follow (these instructions)[https://github.com/luggit/react-native-config#ios-1] in the README? If so, that would explain why your staging file is getting copied into the .env.

**Comment by tareqdayya** [comment]
> Did you follow (these instructions)[https://github.com/luggit/react-native-config#ios-1] in the README? If so, that would explain why your staging file is getting copied into the .env.

Thank u, That was it. A pre-action script was being executed on the build copying .env.staging to .env.
I have no idea how it got there tbh.
