### ISSUE TITLE
Archive has no version

### ISSUE THREAD

**Issue by chj-damon** [luggit/react-native-config#580]
I followed all the steps in the readme about `Availability in Build settings and Info.plist` and `Different environments`, but I don't know why it happened like this:
![image](https://user-images.githubusercontent.com/4902684/120065222-c955a400-c0a2-11eb-9f31-3a4e86abf694.png)

I've configured the pre-action in Archive:
![image](https://user-images.githubusercontent.com/4902684/120065266-f609bb80-c0a2-11eb-90bc-3fbc2b6f5eb7.png)
I know someone would say that it's different from the content:
![image](https://user-images.githubusercontent.com/4902684/120065298-26515a00-c0a3-11eb-8f6f-e29931e4ddbe.png)
But I can confirm that it doesn't work either.

I use two variables in `info.plist`: VERSION_NAME / VERSION_CODE, which are defined in the `.env.xxx` file in the root project.
```code
         <key>CFBundleShortVersionString</key>
	<string>$(VERSION_NAME)</string>
	<key>CFBundleVersion</key>
	<string>$(VERSION_CODE)</string>
```
![image](https://user-images.githubusercontent.com/4902684/120065408-b42d4500-c0a3-11eb-8e80-e379963349c0.png)

**Comment by chj-damon** [comment]
fixed

**Comment by cb-eli** [comment]
Hi, how did you fix this issue?
I'm also trying to use a variable from the `.env` file in the `Info.plist` file but seems like it does not take the value.

**Comment by chj-damon** [comment]
# Type a script or drag a script file from your workspace to insert its path.
cp "${SRCROOT}/../.env.prod" "${PROJECT_DIR}/../.env"
"${SRCROOT}/../node_modules/react-native-config/ios/ReactNativeConfig/BuildXCConfig.rb" "${SRCROOT}/.." "${SRCROOT}/tmp.xcconfig"

**Comment by cb-eli** [comment]
I had this script, but the variable worked only when I installed the app on a simulator. When I installed it on a physical device it didn't work.
I tried to replace `$(MY_VARIABLE)` with `${MY_VARIABLE}` and it worked for some reason... strange.
