### ISSUE TITLE
`react-native-windows` as a peer dep might not be needed?

### ISSUE THREAD

**Issue by pvinis** [luggit/react-native-config#581]
I just tried to use npm 7 to install this package in a mobile RN project with react 16. npm complained that rnw needs react 17 and I have 16 so they are not compatible.

I don't think rnw should be a peer dep, should it? It doesn't provide anything for mobile, and if a project is doing RN on win, then it does have that dep already.

Does that make sense?

**Comment by luancurti** [comment]
Yes, it make sense.

Feel free to contribute 😄
