### ISSUE TITLE
Getting the env variables in custom plist file on iOS

### ISSUE THREAD

**Issue by KawaljeetCuelogic** [luggit/react-native-config#601]
Hello. Thank you for the awesome library.

I have a concern regarding the availability of the environment variables in a custom plist file. I am using App Center for CICD where I have created multiple schemes. I need a different app secret for each scheme. I need to fetch this app secret from the env file in App Center's plist file (AppCenter-Config.plist) and I am currently unable to do it. Here is the code for `AppCenter-Config.plist` file.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
    <key>AppSecret</key>
    <string>$(APP_CENTER_APP_SECRET_IOS)</string>
    </dict>
</plist>
```

I have not added any additional code or script for this, assuming it would be available here as it is in the Info.plist file like this $(MY_ENV_VARIABLE). But unfortunately, this doesn't seem to work.

Is there any way to access env variable in a custom .plist file in iOS?

**Comment by KawaljeetCuelogic** [comment]
Hey @miguel-martinez-6661 . Yes I was able to achieve this by creating a pre build script file for App Center CICD where I created a new file with shell script. 
Say your file `<filename>.plist` looks like this- 
```
<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > 
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\">
<dict>
<key>Key</key>
<string><your-key></string>
</dict>
```

Below is the code that creates a new file at your specified file path (line 1).

```
file="ios/<filename>.plist"
echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > $file
echo "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">" >> $file
echo "<plist version=\"1.0\">" >> $file
echo "<dict>" >> $file
echo "<key>Key</key>" >> $file
echo "<string>${RN_KEY}</string>" >> $file
echo "</plist>" >> $file
printf "\n.custom plist file created with contents:\n\n"
cat $file
```

Where `RN_KEY` is injected from App Center environment variables.
I hope this helps.

**Comment by MaganAnkur** [comment]
I am still facing this issue, accessing variables in custom config file after upgrading to v1.4.6, @luancurti

**Comment by aureosouza** [comment]
We were able to integrate AppCenterReactNative SDK using react-native-config for both Android and iOS without relying on app center variables or running pre build scripts on AppCenter side to populate the AppCenter-Config.plist or android asset with the AppSecret.

We are only using the .env files for each flavour of build (develop, staging and production):.

### Configuring react-native-config: 

1) `npm install react-native-config && npx pod-install`
2) Create your .env files, (we have .env.development, .env.staging & .env.production), each of those with for example:

```
API_URL=API_URL=https://yourapi.development.com
ANDROID_APP_CENTER_SECRET=YOUR_APP_SECRET_HERE
IOS_APP_CENTER_SECRET=YOUR_APP_SECRET_HERE
```

2) For Android in android/app/build.gradle add:

```
project.ext.envConfigFiles = [
  productiondebug: ".env.production",
  productionrelease: ".env.production",
  developmentrelease: ".env.development",
  developmentdebug: ".env.development",
  stagingrelease: ".env.staging",
  stagingdebug: ".env.staging"
]

apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
```

And below the buildTypes:

```
flavorDimensions "default"

productFlavors {
    production {}
    staging {}
    development {}
}
```

3) For iOS In Xcode create your schemes, for example YourAppDevelopment, YourAppStaging & YourAppProduction:

3.1) Product > Scheme > Edit Scheme and `Duplicate Scheme` on the bottom and name it YourAppAppDevelopment and check the shared checkbox (perform for each flavour you need)

3.2) Still on EditScheme, for each flavour select on the left: Build -> Pre-actions -> + -> New Run Script Action, select project from the `Provide build settings` from dropdown. And add under `Type a script or drag a script file`

```
cp "${PROJECT_DIR}/../.env.development" "${PROJECT_DIR}/../.env" 
```

### Configuring appcenter SDK:

1) `npm install appcenter appcenter-analytics appcenter-crashes --save-exact && npx pod-install`
2) For Android on `MainApplication` add on `onCreate` method:

```
import com.microsoft.appcenter.AppCenter;
import com.microsoft.appcenter.analytics.Analytics;
import com.microsoft.appcenter.crashes.Crashes;

...
  @Override
  public void onCreate() {
    ...
    AppCenter.start(this, BuildConfig.ANDROID_APP_CENTER_SECRET, Analytics.class, Crashes.class);
    ...
```

And in `android/app/src/main/res/values/strings.xml` add:

```
<string name="appCenterCrashes_whenToSendCrashes" moduleConfig="true" translatable="false">DO_NOT_ASK_JAVASCRIPT</string>
<string name="appCenterAnalytics_whenToEnableAnalytics" moduleConfig="true" translatable="false">ALWAYS_SEND</string>
```

3) For iOS in `AppDelegate`:

```
#import "ReactNativeConfig.h"
#import <AppCenter/MSACAppCenter.h>
#import <AppCenterReactNativeShared/AppCenterReactNativeShared.h>
#import <AppCenterReactNative.h>
#import <AppCenterReactNativeAnalytics.h>
#import <AppCenterReactNativeCrashes.h>
...
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  ...
  NSString *appSecret = [ReactNativeConfig envFor:@"IOS_APP_CENTER_SECRET"];
  [MSACAppCenter configureWithAppSecret:appSecret]; // Not necessary to call register
  [AppCenterReactNativeAnalytics registerWithInitiallyEnabled:true];
  [AppCenterReactNativeCrashes registerWithAutomaticProcessing];
  ...
```

**And that's it**!

Some advantages of this approach:

1) We do not need to populate multiple AppCenter-Config.plist or android asset and add each file to project with different app secret.
2) We do not rely on AppCenter pre-build to be able to set different flavours, so you can generate the builds outside of AppCenter for each build flavour and have fully functional integration.
3) In this way we follow a clean [single source of truth (SSOT)](https://en.wikipedia.org/wiki/Single_source_of_truth) approach in which all the specific config for each flavour are only the .env files, available for both native or js and not hidden anywhere else.

Sources:

https://www.bigbinary.com/blog/handling-environment-specific-configurations-in-react-native
https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/android
https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/ios
https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/react-native

**Comment by kaylacasale** [comment]
> Hello. Thank you for the awesome library.
> 
> I have a concern regarding the availability of the environment variables in a custom plist file. I am using App Center for CICD where I have created multiple schemes. I need a different app secret for each scheme. I need to fetch this app secret from the env file in App Center's plist file (AppCenter-Config.plist) and I am currently unable to do it. Here is the code for `AppCenter-Config.plist` file.
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
>     <dict>
>     <key>AppSecret</key>
>     <string>$(APP_CENTER_APP_SECRET_IOS)</string>
>     </dict>
> </plist>
> ```
> 
> I have not added any additional code or script for this, assuming it would be available here as it is in the Info.plist file like this $(MY_ENV_VARIABLE). But unfortunately, this doesn't seem to work.
> 
> Is there any way to access env variable in a custom .plist file in iOS?

Okay, I have been also debating my attempt. If I were to fix something, After searching for updated/reliable info, I think I would add curly braces around the enviroment variable name. 
 
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
    <key>AppSecret</key>
    <string>${APP_CENTER_APP_SECRET_IOS}</string>
    </dict>
</plist>
```

How do you import these environment variables dynamically into your app.conifg? It is all interestng, I may be wrong just an opinion.
