### ISSUE TITLE
AppCenter - IOS - during Build got "Missing .env file"

### ISSUE THREAD

**Issue by chenop** [luggit/react-native-config#628]
Its not an issue but something I thought worth mention - maybe other will encounter it as well.

I inject environment variables with appcenter-pre-build.sh
In Android Build everything works fine - in IOS got "Missing .env file"

After investigating the issue it turns out that I got old react-native-config version "0.12.0".
Upgrading it to latest "1.4.5" solved it.

**Comment by lakpriya1s** [comment]
I have the same issue with version 1.4.5, Can you help me with appcenter-pre-build.sh?

```
ENV_FILE=$APPCENTER_SOURCE_DIRECTORY/.env
DEV_ENV_FILE=$APPCENTER_SOURCE_DIRECTORY/.env.dev
STAG_ENV_FILE=$APPCENTER_SOURCE_DIRECTORY/.env.stag
PROD_ENV_FILE=$APPCENTER_SOURCE_DIRECTORY/.env.prod

cp $DEV_ENV_FILE $ENV_FILE
```
