### ISSUE TITLE
Is iOS 8.0 Support?

### ISSUE THREAD

**Issue by PeterRock** [luggit/react-native-config#65]
Xcode noticed like this:

> ld: warning: object file (..../libReactNativeConfig.a(ReactNativeConfig.o)) was built for newer iOS version (9.2) than being linked (8.0)

So, can it work correctly on iOS 8.0?

**Comment by gavaliswapnil** [comment]
**"ReactNativeConfig.h not found"**
I was link ReactNativeConfig package as per documentation but its not link with xcode 8
 please anybody help me

**Comment by vonovak** [comment]
@PeterRock that's just a warning, it will most likely work

**Comment by pesakitan22** [comment]
http://imgur.com/Bt9rrn1
http://imgur.com/4bAsuxS

fatal error

**Comment by loserford** [comment]
@vonovak it's not just a warning, @pesakitan22 is correct. Could you change the target deployment to 8.0? Or we'll need to change it locally.

**Comment by AWrightIV** [comment]
I'm using @patw0929's fork now because his fixes the issue. Please merge it.

**Comment by pedro** [comment]
Oops, sorry for the trouble folks, fixed in 0.7.1.
