### ISSUE TITLE
react-native-web support

### ISSUE THREAD

**Issue by varungupta85** [luggit/react-native-config#650]
I am looking for react-native-web support for this package. I have a mono-repo where the mobile app and the web app are different packages and the business logic is present in some more packages shared between the mobile and the web app. I need to do something in the shared code based on the config present in the `react-native-config` file for which I need `react-native-web` support for this package.

#225 suggests using `react-web-config` but that package doesn't show how to use it with `create-react-app` or `react-app-rewired`.

**Comment by varungupta85** [comment]
No longer needed.

**Comment by HuuNguyen312** [comment]
@varungupta85 Please share with me your solution.

**Comment by marcodafonseca** [comment]
@varungupta85 I'm also keen to know your resolution for this issue

**Comment by goatandsheep** [comment]
[react-native-dotenv](https://github.com/goatandsheep/react-native-dotenv) works with web
