### ISSUE TITLE
ENVFILE is not being set

### ISSUE THREAD

**Issue by rivaros** [luggit/react-native-config#653]
Getting weird behavior on react-native project in MacOS, when running

`ENVFILE=.env.local yarn android`

It still reads eveything from `.env` file, not `.env.local`
> Configure project :app
Reading env from: .env

Looks like in `dotenv.gradle`  `System.env['ENVFILE']` resolves to null, so it does not see the environment variables set in command line.

**Comment by avirankatz** [comment]
@rivaros I'm experiencing the same behavior.
How did you solve this?

**Comment by ThinkSalat** [comment]
Hi, I'm experiencing the same but with both ios and android. Seems like setting the envfile from the terminal isn't working.

**Comment by AngelDev0329** [comment]
I am facing this problem too.
How did you solve this?
