### ISSUE TITLE
Android Release problem with .env

### ISSUE THREAD

**Issue by danieldanielecki** [luggit/react-native-config#655]
I went through the docs quite throughly:
- [setup](https://github.com/luggit/react-native-config#setup)
- [extra steps for Android](https://github.com/luggit/react-native-config#extra-step-for-android)
- [Android](https://github.com/luggit/react-native-config#android)
- [Problems with Proguard](https://github.com/luggit/react-native-config#problems-with-proguard)

Also, through many of the [issues](https://github.com/luggit/react-native-config/issues) and its comments, such us:
- [#326 (comment)](https://github.com/luggit/react-native-config/issues/326#issuecomment-487926673)
- [#400 (comment)](https://github.com/luggit/react-native-config/issues/400#issuecomment-597256368)
- [#532 (comment)](https://github.com/luggit/react-native-config/issues/532#issuecomment-758439076)

and it still doesn't work on  **release** by simply showing a white screen :( the app works fine on `Android` simulator, `Android` physical device with `USB debugging` (I can see `Reading env from: .env`), `iOS` simulator/physical device on localhost/release.
I do have a problem with obtaining `Google Maps API Key` from the `.env` in the `@string/GOOGLE_MAPS_API`/`AndroidManifest.xml`, which causes the white screen. I do build using `expo build:android` instead of `eas build --platform android` due to https://stackoverflow.com/questions/71909541/android-gradle-plugin-requires-java-11-to-run-you-are-currently-using-java-1-8

My commit with all the changes required for all those configs: https://github.com/tamotam-com/tamotam-app/commit/49cb29a588ba0e7ea0f608b071c536ee773c79a9

Therefore, a question, is the package still working? Anyone was able to do so recently?
My versions of packages:
- `classpath('com.android.tools.build:gradle:7.1.1'`
- `"react-native": "0.64.3"`
- `"react-native-config": "^1.4.5"`

**Comment by Mr0cket** [comment]
Yes, I just built with `"react-native-config": "^1.4.5"`, the env file (`.env.develop`) was detected/read successfully.

First of all, you mention it shows a white screen when building release. How are you sure your root problem is due to this library?

If you can answer that with confidence, My suggestion would be to go back to your last good commit (the one before you added all these changes) and try to setup react-native-config there from scratch. 

That way you can be sure none of these unrelated changes are causing any conflicts. Once you have a release build working, add the other changes, until it breaks.

**Comment by danieldanielecki** [comment]
@Mr0cket thanks for your contribution, the problem was `com.android.tools.build:gradle:7.1.1` instead of `com.android.tools.build:gradle:4.1.0` in `build.gradle`, which I have updated while using `Android Studio`... wow!

**Comment by Mr0cket** [comment]
Oh yeah... that sounds like a tough problem to debug. I believe the new gradle plugin `v7.1.1` is only used from RN `v0.67`.

**Comment by Irfanwani** [comment]
How to use it with eas build

**Comment by danieldanielecki** [comment]
@Irfanwani, I've it working on my app, with `eas build`.
Feel free to review the code and implement it by yourself :) https://github.com/tamotam-com/tamotam-app
