### ISSUE TITLE
Overwrite envfile variables with command-line environment variable

### ISSUE THREAD

**Issue by yachaka** [luggit/react-native-config#67]
Hello,
Thanks for the package, works great following README instructions.
I had a question : is it possible to overwrite the `envfile` variables using command-line env variables ?
For example if I had an `envfile` as follow :
```
DEFAULT_USERNAME=mickael@github.com
```
I might for testing want to run the app with a different default username, but only for this run, so I would like to be able to run `DEFAULT_USERNAME=tmp_username@github.com react-native run-platform`.  
Looking at the code, I guess this is not achievable right now with this package ; how would you achieve it ? Do you plan to add this capability to the `build.gradle` file and the ruby file ?

**Comment by alreadysabbir** [comment]
Also wanted to ask the same

**Comment by pedro** [comment]
Interesting! I think the stuff in `.env` should always take precedence. If we allow overrides we might see unexpected conflicts like `USER`, which is set by the shell itself.

For quick tweaks I normally leave commented stuff in my env, like:

```
# VAR=1
VAR=2
```

It's quick enough to toggle, and you can easily see what's going on.

Hope this helps, let me know of any other feedback in this front!

Thanks
