### ISSUE TITLE
[Bug] This library has an incorrect Typescript type

### ISSUE THREAD

**Issue by jaquinocode** [luggit/react-native-config#671]
This line:
https://github.com/luggit/react-native-config/blob/cd1a84e5dbe29a62369cac2f9776de4ae9a4741e/index.d.ts#L2

should instead be:
```js
[name: string]: string | undefined
```

Reason I say that:
The actual behavior of the library is such that any property on the config object will either be a string (if an env variable was set with that property name) or undefined (if that env variable doesn't exist).

But currently, it's typed with the wrong assumption that any property name on the config object exists and is a string, which is definitely not true.

<hr>

This then leads to bad code practices for the library's users. Since we're wrongfully pretending that a config property will never be undefined, then we might not bother (or forget) to check for possibly missing values, leading to unexpected run-time bugs.

The bug fix is an easy 1-line change. Let me know if a PR is welcome, and then I would love to submit one!

**Comment by luancurti** [comment]
Fixed in `1.4.7`

**Comment by jaquinocode** [comment]
@luancurti Thanks, I really appreciate it! 😄👍
