### ISSUE TITLE
How can change my full aplication id, using react-native-config

### ISSUE THREAD

**Issue by Ellathet** [luggit/react-native-config#685]
Hello, in one of my projects using react-native-config, I needed change my applicationId, but qhen i change in gradlew, like this:

`defaultConfig {
    applicationId project.env.get("APP_ID")
}`

React native return to me a error, saying it couldn't find MainActivity with my new id and recommending taking the applicationId from gradlew. 

What can I do?

**Comment by luancurti** [comment]
@Ellathet Can you share the error? 

It would be good if you have a reproducible demo

**Comment by Ellathet** [comment]
Oh, sorry, for shure. Let me show you, when start my app using a flavor where a change AppId:

```groovy
productFlavors {
    examplehml {
        applicationId "br.com.example"
        dimension "default"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        resValue 'string', 'app_name', project.env.get('APP_COMPANY_NAME')
    }
```
and put this line in my script in `package.json`:
```json
"scripts": {
    "android:exampleFlavor": "react-native run-android --variant=examplehml debug --appId=br.com.example"
}
```
and then React couldn't find the main application. Could not return to an old version, to show the error, but I managed to fix it, I put this line in my `defaultConfigs` in `build.gradlew`, referencing to my package name in `Manifest.xml`:
```groovy
defaultConfig {
        resValue "string", "build_config_package", "my.manifest.package.name"
}
```

and this rules, in my `proguard-rules.pro`:
```pro
-keep class br.com.wideedu.BuildConfig { *; }
```

And then react recognized the main class. I just couldn't identify what was the change that made him recognize! 
Tanks for helping! 

Obg pela ajuda, acho qeu foi falta de atenção minha por ver a parte do `build_config_package`! 🤯

**Comment by luancurti** [comment]
Yes, if the `app_name` is different of the `build_config_package` and you use the `app_name` in the `build_config_package` the `env` don't load correctly!

Your welcome!
