### ISSUE TITLE
automatically loading .env.development and creating tmp.xcconfig - ignoring all other .env files (1.4.2)

### ISSUE THREAD

**Issue by rizshivalli** [luggit/react-native-config#686]
Not sure why this is happening in iOS

no matter which configuration i select (dev, staging, prod) the Xcode is still using the .env.development file to create the archives 

according to documents it should select the respective .env file but the tmp.xcconfig is getting generated only from .env.development no matter what configuration i select.

I have tried renaming the files to .env.dev, .env.stage, .env.prod suggested in #679  but still the issue persists.

is there any reason why this is happening?

**Comment by rizshivalli** [comment]
before archiving i run react-native run-ios --scheme SCHEME_NAME and then archive from xcode

**Comment by henaharon** [comment]
Hey ! @rizshivalli :)
How did you solve it? Its exactly whats Im experiencing
