### ISSUE TITLE
Android: Config is not accessible from React Native App level (React 0.70.2)

### ISSUE THREAD

**Issue by NotArtyom** [luggit/react-native-config#688]
## Description
```
After importing Config on the React Native level, the Config remains empty {} and 
any value from the config is undefined, however on the native android level everything works fine.
This issue is related only to android platform. For IOS - everything also works fine

```
## Steps to reproduce
-  Add React Native Config dependency
-  [Complete extra step for Android](https://github.com/luggit/react-native-config#extra-step-for-android)
-  Check if the Config works on the Android Native level
-  import Config from "react-native-config" on React Native level
-  Log any value from env file and receive undefined 

## RN Config Version
```"react-native-config": "^1.4.6"```

## React Native Version
```
"react-native": "0.70.2"
```
```
New Architerture: disabled 
Hermes: enabled
```

## Plaform
```Android```

## Workflow
```React Native without Expo (RN CLI)```

## Architecture
```Old Architecture```

**Comment by flogy** [comment]
Experiencing the same issue with the same RN version.

**Comment by NoahSimajji** [comment]
What is happening?

**Comment by surajSanwal** [comment]
hey @NoahSimajji , I implemented this around 6 months back and it was working as expected, my android package has 3 flavors, and for each, we have .env, .env.production, .env.staging  
right now when android is accessing the env config it is working fine, but when I am using env variables In JS code it returns undefined and Config is returning a blank object. 
```js 
     project.ext.envConfigFiles = [
        debug: ".env",
        production: ".env.production",
        beta:".env.staging",
        anothercustombuild: ".env",
]


apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

defaultConfig {
        applicationId "com"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode project.env.get("ANDROID_VERSION_CODE").toInteger()
        versionName project.env.get("ANDROID_VERSION_NAME").toString()
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
        // react-native-iap: we only use the Google Play flavor
        missingDimensionStrategy 'store', 'play'
        resValue "string", "build_config_package", "com.package_name"
    }
 
  productFlavors {
        production {
            applicationIdSuffix project.env.get("ANDROID_BUNDLE_SUFFIX").toString()
        }
        beta {
            applicationIdSuffix project.env.get("ANDROID_BUNDLE_SUFFIX").toString()
            // We can have build-specific configurations here. Like using applicationIdSuffix to create different package name (ex. ".staging")
        }
        development {
            applicationIdSuffix project.env.get("ANDROID_BUNDLE_SUFFIX").toString()
        }
        googlePlay{
            dimension "appstore"
            missingDimensionStrategy "store", "play"
        }
    }

```

**Comment by zed-em1** [comment]
Facing same issue in react-native 0.68.2

**Comment by MBach** [comment]
Ah OK I was wondering why my API calls were suddenly failing despite it's working in Postman... It always works with Postman :)

**Comment by surajSanwal** [comment]
any update here, this issue has been going on for so long, any maintainers are looking into this?

**Comment by Vepsur** [comment]
I have the same problem. 😔

**Comment by justin-tay** [comment]
I have attempted to repro this with a clean project with the following versions but don't see this issue. 

`"react-native": "0.70.3",
"react-native-config": "^1.4.11"`

This is Android, React Native without Expo, Hermes enabled, Old Architecture.

![react-native-config](https://user-images.githubusercontent.com/49700559/196637171-7ebfc04f-f070-4a78-bc16-fad2ad97ec97.png)

**Comment by NotArtyom** [comment]
@justin-tay 
Can you show your build.gradle please? 
Probably there are some differences in implementation of different flavors

**Comment by NotArtyom** [comment]
I returned to the problem today and found out, that my problem was related to this the advanced step

```
defaultConfig {
    ...
    resValue "string", "build_config_package", "YOUR_PACKAGE_NAME_IN_ANDROIDMANIFEST_XML"
}
```

I implemented this line like 

```
resValue "string", "build_config_package", applicationId
```

Where applicationId is a variable which contains value from manifest package. And it simply had a typo in the package name, so the package name was incorrect and the config was not accessible from app level.

**Comment by caolong0204** [comment]
i'm facing same issue, but there isn't any typo in my code

**Comment by SanjanaTailor** [comment]
I am also facing same issue 
React-native - 0.68.3
"react-native-config": "^1.4.11",

**Comment by SanjanaTailor** [comment]
> ny typo in my cod

I am also facing same issue, any solution ?

**Comment by Jojr** [comment]
I'm running RN v0.70.6 and I solve that just by putting the code below at the beginning of `android/app/build.gradle`:

`apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"`

![Captura de Tela 2023-05-12 às 15 37 32](https://github.com/luggit/react-native-config/assets/8437807/fc6bd479-e2ae-4b7f-afc3-7b6d9c9fe2c0)

Maybe it can help someone :)

**Comment by anhdo9797** [comment]
> hey @NoahSimajji , I implemented this around 6 months back and it was working as expected, my android package has 3 flavors, and for each, we have .env, .env.production, .env.staging right now when android is accessing the env config it is working fine, but when I am using env variables In JS code it returns undefined and Config is returning a blank object.
> 
> ```java
>      project.ext.envConfigFiles = [
>         debug: ".env",
>         production: ".env.production",
>         beta:".env.staging",
>         anothercustombuild: ".env",
> ]
> 
> 
> apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
> 
> defaultConfig {
>         applicationId "com"
>         minSdkVersion rootProject.ext.minSdkVersion
>         targetSdkVersion rootProject.ext.targetSdkVersion
>         versionCode project.env.get("ANDROID_VERSION_CODE").toInteger()
>         versionName project.env.get("ANDROID_VERSION_NAME").toString()
>         multiDexEnabled true
>         vectorDrawables.useSupportLibrary = true
>         // react-native-iap: we only use the Google Play flavor
>         missingDimensionStrategy 'store', 'play'
>         resValue "string", "build_config_package", "com.package_name"
>     }
>  
>   productFlavors {
>         production {
>             applicationIdSuffix project.env.get("ANDROID_BUNDLE_SUFFIX").toString()
>         }
>         beta {
>             applicationIdSuffix project.env.get("ANDROID_BUNDLE_SUFFIX").toString()
>             // We can have build-specific configurations here. Like using applicationIdSuffix to create different package name (ex. ".staging")
>         }
>         development {
>             applicationIdSuffix project.env.get("ANDROID_BUNDLE_SUFFIX").toString()
>         }
>         googlePlay{
>             dimension "appstore"
>             missingDimensionStrategy "store", "play"
>         }
>     }
> ```
> 
> ```js
>     "react": "17.0.2",
>     "react-i18next": "^11.17.0",
>     "react-native": "0.67.3",
>      "react-native-config": "^1.4.6",
> ```
> 
> ```js
>      
> "use strict";
> import Config from "react-native-config";
> 
> export const APP_ENV = Config.APP_ENV as envType;
> export const API_URL = Config.API_URL;
> export const BASE_URL = Config.BASE_URL;
> export const SOCKET_URL = Config.SOCKET_URL;
> export const BUCKET_URL = Config.BUCKET_URL;
> export const API_VERSION = Config.API_VERSION;
> export const API_PATH = Config.API_PATH;
> export const SOCKET_PATH = Config.SOCKET_PATH;
> export const SOCKET_SSL = Config.SOCKET_SSL;
> export const BUCKET_SSL = Config.BUCKET_SSL;
> export const WEB_SSL = Config.WEB_SSL;
> export const API_SSL = Config.API_SSL;
> export const PROD_APP_VERSION = Config.PROD_APP_VERSION;
> ```
> 
> all are undefined

I have same issue with ` "react-native": "0.71.8"`
