### ISSUE TITLE
Question: When bundling app

### ISSUE THREAD

**Issue by alixeb** [luggit/react-native-config#69]
Hello,

It looks like that when you run `react-native bundle ...etc...` it reads the `.env` file even if you do `ENVFILE=.env.local react-native bundle ...etc..`

Is there a way around?

**Comment by MyGuySi** [comment]
Did you find a solution to your issue? I'm evaluating a few libraries and would like to know how to handle bundling different environments

**Comment by alixeb** [comment]
@MyGuySi we didn't use this repo.
We ended up putting various commands in `scripts` in package.json to suit our need.
