### ISSUE TITLE
Value Not Found A CFBundleIdentifier iOS

### ISSUE THREAD

**Issue by Ellathet** [luggit/react-native-config#694]
Hi, i tried to make a white-label app for iOS in react-native, for this I used react-native config. I did the initial configuration:

- I created `Config` file to includ `tmp.xconfig`
- Put Pre script in scheme:
```sh
"${SRCROOT}/../node_modules/react-native-config/ios/ReactNativeConfig/BuildXCConfig.rb" "${SRCROOT}/.." "${SRCROOT}/tmp.xcconfig"
```
- And script to replace my .env file by scheme

But when try change `Bundle identifier`:
![image](https://user-images.githubusercontent.com/76699403/197788233-6b8082d5-6757-46d4-85ac-e05b6db264d5.png)

The build error is:
![image](https://user-images.githubusercontent.com/76699403/197788496-1c5baab7-c6d3-4390-833e-84b7222e7692.png)

Other way to make this is using the same name of variable, for example, in my `.env`:
```env
...
PRODUCT_BUNDLE_IDENTIFIER=br.com.example
```
In theory, it overlaps by Config file. Is there a way to change my Bundle identifier?

**Comment by Ellathet** [comment]
My solution to change the Bundle id, was to create a project with a copy of my target, thus creating different Infos.plit!

**Comment by justin-tay** [comment]
It's not really clear if you performed all the necessary steps.
- Go to project settings
- Apply config to your configurations

![3 ios_apply_config](https://user-images.githubusercontent.com/49700559/198211049-78027b5e-4d45-4270-bd9c-aee655086a4f.png)

**Comment by Ellathet** [comment]
I did that, but not run yet.
