### ISSUE TITLE
.env on development mode undefined

### ISSUE THREAD

**Issue by decoderid** [luggit/react-native-config#714]
# SOLVED
```js
import {Config} from 'react-native-config'
```

# INTRO
I have a problem with this package, it can't be used in typescript code, the result is **undefined**, I want to use **Config.API_URL** together with **Axios Instance**

### Example
```js
import Config from 'react-native-config'
import axios from 'axios';

const api = {
  main: axios.create({
    baseURL: Config.API_URL,
    timeout: 10000
  }),
  blog: axios.create({
    baseURL: Config.BLOG_URL,
    timeout: 10000
  })
};

console.log(Config.API_URL)

export default api
````
### Result
```bash
 # LOG  undefined 
 # [AxiosError: Network Error]
```

### Expectation
```bash
# LOG https://api.example.com
```

### Version
```json
{
"depedencies":
    "react-native-config": "^1.4.11",
}
```

**Comment by rahmat-st** [comment]
hi @decoderid, I've try to use `import {Config} from 'react-native-config'`, but it still undefined for me

**Comment by decoderid** [comment]
> hi @decoderid, I've try to use `import {Config} from 'react-native-config'`, but it still undefined for me

try to clean and rebuild

**Comment by caiqueex** [comment]
same here, in prod works fine, but in dev, doesnt :/
