### ISSUE TITLE
How to use this with eas build

### ISSUE THREAD

**Issue by Irfanwani** [luggit/react-native-config#716]
How can we use this with eas build so the env gets loaded in the eas builds.

**Comment by Irfanwani** [comment]
I found another way of implementing env in an expo project, i used dotenv (yarn add dotenv), then in your app.config.js (you need dynamic config for this);

`import "dotenv/config"
export default {
  expo: {
   ...,
    extra: {
      BASE_URL: process.env.BASE_URL,
    },
  }
}`

And then in any file in your project, you can access the `BASE_URL`  (taking as an example) as;

`import Constants from 'expo-constants'

let Baseurl = Constants.manifest.extra.BASE_URL`

Note that, you need to create a .env file in the root directory of your project from where the dotenv will read the env variables like BASE_URL.

Also, this will work with both expo build as well as eas production build.

**Comment by tsdmrfth** [comment]
I still need to use this library as I'm accessing environment variables in native code. Above solution doesn't work with native code...
