### ISSUE TITLE
Could not determine the dependencies of task ':app:processReleaseManifest'.

### ISSUE THREAD

**Issue by eds9nsilva** [luggit/react-native-config#717]
Has anyone had this problem too? On running AppCenter
<img width="745" alt="Captura de Tela 2023-01-09 às 15 31 42" src="https://user-images.githubusercontent.com/51426467/211382315-a2016081-563a-4162-9dcc-e0064f819ee9.png">

Error:
> Failed to query the value of task ':app:processReleaseManifest' property 'mainMergedManifest'.
   > Could not create task ':app:processReleaseMainManifest'.
      > java.lang.NullPointerException (no error message)

My defaultConfig in Android/app/build.gradle
`  defaultConfig {
        applicationId "com.myProjetct"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        manifestPlaceholders=[API_KEY_GOOGLE_MAPS:project.env.get("API_KEY_GOOGLE_MAPS")]
        multiDexEnabled true
    }
`

My AndroidManifest.xml
  `<meta-data android:name="com.google.android.geo.API_KEY"android:value="@string/API_KEY_GOOGLE_MAPS"/>`

**Comment by eds9nsilva** [comment]
<img width="745" alt="Captura de Tela 2023-01-09 às 15 31 42" src="https://user-images.githubusercontent.com/51426467/211382074-bb43a9f0-a75c-4f58-b2eb-d2beadb4722a.png">

**Comment by junaidstatiq** [comment]
hello can you please share the solution if you get

**Comment by MarcelleBond** [comment]
Can you please share the solution to this issue

**Comment by eds9nsilva** [comment]
> Can you please share the solution to this issue
> hello can you please share the solution if you get

The solution was to add the environment check before adding the variable to the defaultConfig. 
file: android/app/build.gradle

`
def REACT_NATIVE_API_KEY_GOOGLE_MAPS = System.getenv("REACT_NATIVE_API_KEY_GOOGLE_MAPS")

if ( REACT_NATIVE_API_KEY_GOOGLE_MAPS == null) {
    REACT_NATIVE_API_KEY_GOOGLE_MAPS = project.env.get("REACT_NATIVE_API_KEY_GOOGLE_MAPS")
}
`

After doing this check, add the manifestPlaceholders variable to defaultConfigs

`       
 manifestPlaceholders["REACT_NATIVE_API_KEY_GOOGLE_MAPS"] = REACT_NATIVE_API_KEY_GOOGLE_MAPS
`

**Comment by MarcelleBond** [comment]
Thank you
