### ISSUE TITLE
build error on ios device when enter 'yarn react-native run-ios' command

### ISSUE THREAD

**Issue by yunyami0605** [luggit/react-native-config#718]
### environment
"react": "18.1.0",
"react-native": "0.70.3",
"react-native-config": "^1.4.11"

### problem
build error comes up when enter 'yarn react-native run ios' (= yarn ios) command on the vscode

### error
```
warning: Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'daesodong' from project 'daesodong')
warning: Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'daesodong' from project 'daesodong')

** BUILD FAILED **


The following build commands failed:
        PhaseScriptExecution [CP-User]\ Config\ codegen /Users/cookie/####/Developer/Xcode/DerivedData/####-encgjdoyhlanbofkoxoagoqingng/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-config.build/Script-46EB2E0001CC10.sh (in target 'react-native-config' from project 'Pods')
(1 failure)
```

### special note
it works fine on android and xcode build process
.env file has no blank sentence

how to solve this problem?

**Comment by yunyami0605** [comment]
i solve to change version 1.4.6

**Comment by kyjprograming** [comment]
I saw this postings at fun. There seem to latest version be a lot of bugs and errors in any module haha.

**Comment by mthahzan** [comment]
Is there a fix for this? I am seeing this problem after upgrading the React Native version to 0.71.2 and React Native Config version to 1.5.0. I prefer to not downgrade RN Config if at all possible.

**Comment by glennweb** [comment]
For me it all turned out to be a mismatch between the version of ruby in `.ruby-version`. And the version visible rbenv global.

**Comment by yevi04** [comment]
@glennweb It is really nice answer. I saw good. LGTM
