### ISSUE TITLE
Release v1.5.0 has undocumented breaking change

### ISSUE THREAD

**Issue by inyono** [luggit/react-native-config#727]
After updating to v1.5.0, you have to change `import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;` to `import com.lugg.RNCConfig.RNCConfigPackage;`.

Note also that the setup section in the README is therefore out-of-date.

**Comment by ChrisNg02655332** [comment]
Thanks bro! you saved me

**Comment by luancurti** [comment]
Fixed by #728

**Comment by ThomasStubbe** [comment]
This should have been a major change... 

https://phoenixnap.com/kb/package-json#ftoc-heading-5
