### ISSUE TITLE
deployed environment not processing production variables

### ISSUE THREAD

**Issue by AVEmedia** [luggit/react-native-config#74]
it instantly crashes my app when I go to fabric fastlane it to TestFlight (cannot process production env variables)… which is odd behavior because it works perfectly on my local machine, and xcode lets me seamlessly toggle between dev and production variables using schemas. But if flawlessly working locally, do you have any clues as to why it’s not processing env production variables when deployed? fastlane does not overlook any changes made to projects in xcode, and logs are not leaving any clues

**Comment by kevinnguy** [comment]
@AVEmedia what does your Fastfile look like for iOS? I use Fastlane and it works fine for me.

**Comment by mabounassif** [comment]
@AVEmedia Are you using `ENVFILE`?
@kevinnguy are you using the default `.env`?

Based on https://github.com/shakepay/react-native-config/blob/master/ios/ReactNativeConfig/BuildDotenvConfig.ruby there's no support for `ENVFILE` which can explain the difference.

**Comment by mabounassif** [comment]
Addressed by this PR: https://github.com/luggit/react-native-config/pull/145

**Comment by pedro** [comment]
Thanks folks!
