### ISSUE TITLE
import com.lugg.ReactNativeConfig.ReactNativeConfigPackage dont exist

### ISSUE THREAD

**Issue by ChampiMagic** [luggit/react-native-config#746]
System:

OS --> Windows 11
React Native --> 0.71

![Captura de pantalla 2023-03-31 080456](https://user-images.githubusercontent.com/97173716/229104025-bad26493-b184-4d71-930f-950d3607a801.png)

My settings.gradle
![Captura de pantalla 2023-03-31 080622](https://user-images.githubusercontent.com/97173716/229104190-453d02c8-cfb6-4a56-a8e6-25cf64c436bb.png)

My build.gralde
![Captura de pantalla 2023-03-31 080716](https://user-images.githubusercontent.com/97173716/229104477-2a9057d2-6f36-4263-b9c7-56ea66017833.png)
![Captura de pantalla 2023-03-31 080748](https://user-images.githubusercontent.com/97173716/229104497-f3e37f51-ff16-4282-8802-4479258ae40a.png)

My MainAplication.java
![Captura de pantalla 2023-03-31 081232](https://user-images.githubusercontent.com/97173716/229105458-0a893fde-1a3c-44b2-9ee9-0877b6ec9e37.png)

**Comment by gur22-09** [comment]
+1 facing the same issue 

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileProdDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by luancurti** [comment]
@gur22-09 @ChampiMagic 

The Package Was Renamed
```
com.lugg.ReactNativeConfig
```
to

```
com.lugg.RNCConfig
```

Because name collision with the React Native Config internal package

then the import should be **com.lugg.RNCConfig.ReactNativeConfigPackage**

**Comment by gur22-09** [comment]
thanks @luancurti

**Comment by jahau** [comment]
The correct config is: import com.lugg.RNCConfig.RNCConfigPackage;

The screenshot is having it right though.
