### ISSUE TITLE
Switch two projects don't generate content in the file GeneratedDotEnv

### ISSUE THREAD

**Issue by LuckyBoy124** [luggit/react-native-config#748]
I have a problem:
- Every time I change to another project, but when I return to the old project, the content in the GeneratedDotEnv file does not have the content in the .env file and I have to turn off the computer for a while to be able to run it. 
- Please help me with this problem
Thank you very much!

**Comment by MuhammadMuzammilQadri** [comment]
We also have found an issue in which GeneratedDotEnv didn't contain any content, or didn't update it in some cases. So the solution that we found was to delete this file and then run `npm install` and `pod install` again.
