### ISSUE TITLE
[iOS] Trouble installing iOS in general

### ISSUE THREAD

**Issue by vongohren** [luggit/react-native-config#76]
I can't seem to get nothing but an empty config object in my app on iOS. In android it works fine.

I have installed through npm, I have run link, have verified the files for ReactNativeConfig is in my project, by searching for its files. Tried to set up the the info.plist setup, ran pod update, but still, its very empty.

Any suggestions? I have not done anything else

**Comment by dwilt** [comment]
@Snorlock put together a video showing everything I did: https://www.youtube.com/watch?v=VtrumM39wEg

**Comment by Snorlock** [comment]
Thats fucking amazing that you made this video! Thanks dude! I looked through it and I have done it all except for the schemas. I tried to just get it running with the default file .env. But as mentioned it's still empty. Did you ever try the default file? I will look at this more closely on monday, and see how introducing schemas works for me. Im currently off work for the weekend.

**Comment by dwilt** [comment]
No problem. What do you mean - the default file?

**Comment by Snorlock** [comment]
He writes that if you just use a .env file. Then that will be a default file of the whole setup. Then you dont need schemase and stuff. Its in the README

**Comment by Snorlock** [comment]
The weird thing is that I do all these things, firstly iv just used the "main" schema and trying just to get my .env.staging file in and through to the web. Iv verified that the ruby script actually picks up the file and converts to key values and creates the genereatedConfig Object-C class with the right values and everything, but I stille cant get it out to the web for some reason. Works fine on android.

**Comment by Snorlock** [comment]
Ok, I think that iv figuerd out what is the problem. We are running cocoapods and this creates problems for npm link and usage. The file is generated and all through the build and the ruby script, but I guess it's not included proparly. @pedro do you have any input on this?

**Comment by CoreyAR** [comment]
I also ran into a similar issue with version 0.3.0. I had another project using 0.1.0 that I know works and was able to solve this issue by downgrading versions. I have not investigated why the problem occurs yet.

**Comment by CoreyAR** [comment]
Solved the issue. Problem was caused by spaces in my .env file.

**Comment by Snorlock** [comment]
I ended up creating my own: https://bitbucket.org/enturas/react-native-config-swift

**Comment by hiaw** [comment]
Anyway we can merge the Swift version back in here?

**Comment by vongohren** [comment]
Think you can use the one on bitbucket pretty straight out.
But we ended up writing ourselves from swift to C# because it was tooo many problems with updating when having swift in the bottom

**Comment by vongohren** [comment]
Closing now because solutions have been made
