### ISSUE TITLE
0.2.2 Not semantic versioning

### ISSUE THREAD

**Issue by edmundito** [luggit/react-native-config#77]
I ran into an issue this where my project could not build because it has not been migrated to react native 0.40. However, 0.2.2 introduces a fixes that are specific to 0.40 and break compatibility with previous versions, so ideally it should have been versioned at 0.3.0 if it follows http://semver.org guidelines.

**Comment by pedro** [comment]
Hey, sorry for the trouble! We actually do follow semver, but since the major version is 0 the public API is not to be considered stable. That said 0.3 would be a better release indeed 😬 . Would it still help to release 0.3?

**Comment by pedro** [comment]
fwiw we've moved the 0.40 changes to `0.3`, and kept `0.2` intact
