### ISSUE TITLE
[iOS] Help for RN < 0.40

### ISSUE THREAD

**Issue by jonathanlie94** [luggit/react-native-config#78]
I'm having trouble linking the module for my project.

React: 15.3.0
RN: 0.33.0

Everything is working fine for Android, but I could not get the setup done for iOS.

Ran react-native link react-native-config.

The error is basically on the file _ios/ReactNativeConfig/ReactNativeConfig.h_, line 1. It does not know where to find RCTBridgeModule.h. Any suggestions on how to fix this?

**Comment by jonathanlie94** [comment]
For anyone having the same problem, just degrade to a previous version of the library, namely 0.2.1.

**Comment by sectorf8** [comment]
@jonathanlie94 thanks!
