### ISSUE TITLE
iOS build config suggestion

### ISSUE THREAD

**Issue by thadcodes** [luggit/react-native-config#8]
I am not an iOS developer so I'm not certain how to do this exactly but I know it's possible to pass environment variables for the build to xcode as extra parameters.  So Perhaps it might be worth it to add that as an option for setting the environment file, just pass ENVFILE into the build or set it in the scheme?

I'll try to learn enough to do it myself later but I don't know ruby so it might take a while

**Comment by dlupu** [comment]
having the same problem here if someone could help it would be great  (I'm a XCODE newbie)

**Comment by charlires** [comment]
Here it goes some useful links you can get ideas from.

https://joystate.wordpress.com/2015/08/18/use-dynamic-user-variable-with-xcodebuild/
http://bogardon.github.io/xcode/environment-variables/2013/05/20/configuring-env-variables-in-xcode.html

**Comment by jadidian** [comment]
Still not sure, but I guess `xcconfig` could be a solution...
()[http://www.jontolof.com/cocoa/using-xcconfig-files-for-you-xcode-project/]

**Comment by jadidian** [comment]
I think its just possible to add a `.xcconfig` extension to env files, like `.env.production.xcconfig` and then use them as Xcode configuration files, explained here http://www.jontolof.com/cocoa/using-xcconfig-files-for-you-xcode-project/

**Comment by jadidian** [comment]
Yeah, just tried it and it works like magic... only thing you have to do is adding `.xcconfig` to env files, drag and drop them into Xcode (don't make a copy, just reference) and then use them as configuration for each scheme, then you can use the variable names inside your `Info.plist` like
```xml
	<key>CFBundleIdentifier</key>
	<string>$(MY_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(MY_PRODUCT_NAME)</string>
```

**Comment by aymericbouzy** [comment]
I've been using this advice, it works well: http://stackoverflow.com/questions/15857285/find-the-xcode-build-scheme-name-at-run-time/26433618#26433618

**Comment by aymericbouzy** [comment]
I've written a fuller solution on StackOverflow : http://stackoverflow.com/questions/38355034/release-debug-configuration-in-react-native/38356961#38356961

**Comment by pedro** [comment]
Right on – if I was writing an ios-only app I'd probably just go with `.xcconfig` files.

Would also like to use these files to tell react-native-config which `.env` file to read, but wasn't able to get that going last I tried!

Ideally what I'd LOVE to do is to generate a `.xcconfig` file from `.env` on build time, but that doesn't seem to be possible... So long story short we are still missing a good way to integrate `.env` with iOS. [You can read some of the previous discussion on this here](https://github.com/luggit/react-native-config/issues/6).

Closing this in favor of #6 then! Follow up there if you have any ideas on how to improve this.

Thanks,

**Comment by leethree** [comment]
@pedro I just tried to create a symbolic `ios/env.xcconfig -> .env` and set it as base configuration of Xcode target. It seems to work fine.

**Comment by grifotv** [comment]
@jadidian you said `...and then use them as configuration for each scheme...`, how did you each `.env.xcconfig` for each scheme?

**Comment by jadidian** [comment]
@grifotv I called my config files `development.xcconfig`, `staging.xcconfig` and `production.xcconfig`, see the screenshot
![screen shot 2017-09-12 at 5 08 23 pm](https://user-images.githubusercontent.com/650099/30326479-e71e3ffc-97dd-11e7-82e7-f56d75659cf0.png)
when you specify these configuration files for each environment all the values will be available to Xcode, you can use them in `Info.plist` like `$(MY_VARIABLE_NAME)` etc.

**Comment by grifotv** [comment]
@jadidian thanks for that - I'm having a hard time making it work with Bundle ID key in `Info.plist`, for all the other keys it replaces as expected.

Here's something else I tried without success https://github.com/luggit/react-native-config/issues/156

**Comment by leethree** [comment]
@grifotv have you tried to set the `PRODUCT_BUNDLE_IDENTIFIER` in `.xcconfig`?

The section in `Info.plist` should be like this:
```xml
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
```

This works for me.
