### ISSUE TITLE
Cannot link ?

### ISSUE THREAD

**Issue by stilllife00** [luggit/react-native-config#80]
When I run

    react-native link react-native-config

I get 

     rnpm-install ERR! ERRPACKAGEJSON No package found. Are you sure it's a React Native project?
     Cannot read property 'replace' of undefined

The build works fine but the Config returns an empty object `{}`

Any idea ?

**Comment by j2kun** [comment]
I get a similar error:

```
$ react-native link react-native-config
rnpm-install info Linking react-native-config android dependency 
rnpm-install info Android module react-native-config has been successfully linked 
rnpm-install info Linking react-native-config ios dependency 
rnpm-install ERR! It seems something went wrong while linking. Error: str.replace is not a function 
Please file an issue here: https://github.com/facebook/react-native/issues 

str.replace is not a function
```

Version info:

```
$ react-native --version
react-native-cli: 2.0.1
react-native: 0.40.0
```

**Comment by j2kun** [comment]
Did not have the same issue when using `rnpm`, btw.

**Comment by j2kun** [comment]
Contrary to my prior comment, using `rnpm` was a bad idea. Instead I followed the steps here to manually link react-native-config as a workaround:

https://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by pedro** [comment]
:+1: I think this should work normally on the latest, let me know if not!

Thanks folks
