### ISSUE TITLE
Undefined Config in Android when applicationIdSuffix is used

### ISSUE THREAD

**Issue by Villux** [luggit/react-native-config#88]
My setup uses applicationIdSuffix `.master` for test environment. When I'm build a version of the app with that suffix, I get empty`Config` object in the JS side. If I remove suffix everything works as expected. Is there a same way to include env variables also for builds that use different applicationId?

**Comment by mauriciocoelho** [comment]
+1

**Comment by hubciorz** [comment]
+1

**Comment by Villux** [comment]
How did I miss that... thanks!
