### ISSUE TITLE
Please specify in the readme that v0.3.1 is RN 0.40+

### ISSUE THREAD

**Issue by JasperStam** [luggit/react-native-config#90]
Pull request #72 added support for RN 0.40+ but broke support for the earlier versions.
This however is not visible in the README.

Could you specify in the readme to prevent future headache that for RN <0.40 you have to use v0.2?

**Comment by eugenehp** [comment]
Yes! Indeed https://twitter.com/HPEugene/status/859430085723648000 @JasperStam

**Comment by pedro** [comment]
We eventually added compat to <0.40 back, so should be good for now.

I'm hoping we can make this stable enough to avoid a compatibility table, but if not will prob add one next release (: thanks!
