### ISSUE TITLE
Android: Config is undefined (with react-native-navigation)

### ISSUE THREAD

**Issue by tywoodpav** [luggit/react-native-config#95]
Config works as expected on iOS but when I run it on Android, Config.FOO_BAR is undefined.

My `package.json` dependencies are:

    "react": "~15.4.1",
    "react-native": "^0.40.0",
    "react-native-config": "^0.3.1",
    "react-native-navigation": "^2.0.0-experimental.252"

My app module `build.gradle` uses `compileSdkVersion 25` and `buildToolsVersion "25.0.1"`.

The `build.gradle` dependencies are: 

    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:25.0.1"
    compile "com.facebook.react:react-native:+"
    compile project(':react-native-config')
    compile project(':react-native-navigation')

Perhaps it is my `MainActivity.java` or `MainApplication.java` having trouble loading react-native-config due to react-native-navigation?

My `MainActivity.java` is: 

    package com.myproj;

    import com.reactnativenavigation.controllers.SplashActivity;

    public class MainActivity extends SplashActivity {

    }

My `MainApplication.java` is:

    package com.myproj;

    import android.support.annotation.Nullable;

    import com.facebook.react.ReactPackage;
    import com.facebook.react.shell.MainReactPackage;
    import com.reactnativenavigation.NavigationApplication;
    import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;

    import java.util.List;
    import java.util.Arrays;

    public class MainApplication extends NavigationApplication {

      @Override
      public boolean isDebug() {
        return BuildConfig.DEBUG;
      }

      @Nullable
      @Override
      public List<ReactPackage> createAdditionalReactPackages() {
        return null;
      }

      protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new ReactNativeConfigPackage()
        );
      }

    }

Thanks!

**Comment by tywoodpav** [comment]
As suspected, it was a problem due to `react-native-navigation`. Changing `MainApplication.java` to this solved the problem. The issue was caused by `createAdditionalReactPackages` and `getPackages`.

    package com.myproj;

    import com.facebook.react.ReactPackage;
    import com.reactnativenavigation.NavigationApplication;
    import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;

    import android.support.annotation.Nullable;
    import java.util.List;
    import java.util.Arrays;

    public class MainApplication extends NavigationApplication {

      @Override
      public boolean isDebug() {
        return BuildConfig.DEBUG;
      }

      @Nullable
      @Override
      public List<ReactPackage> createAdditionalReactPackages() {
        return Arrays.<ReactPackage>asList(
            new ReactNativeConfigPackage()
            // specify additional packages here
        );
      }

    }

**Comment by pokonski** [comment]
@tywoodpav thanks for posting this solution, I just encountered the same issue :+1:

**Comment by jtibbertsma** [comment]
@tywoodpav Sir, you are a gentleman and a scholar

**Comment by cgx9** [comment]
@tywoodpav i have this issue too,but i use react-navigation
